OpenNebula/one

share/pkgs/Debian/opennebula
share/pkgs/Ubuntu/opennebula

Debian with insserv use dependency based boot sequence.
“Required-Start” and “Required-Stop” can not be used because MySQL may
not be available.
* share/pkgs/Debian/opennebula: Add the “Should-Start” and “Should-Stop”
on MySQL.
* share/pkgs/Ubuntu/opennebula: Ditoo.

Debian init: add optional dependency on mysql

---

share/pkgs/CentOS/opennebula.sudoers
share/pkgs/Debian/opennebula.sudoers
share/pkgs/Ubuntu/opennebula.sudoers
share/pkgs/openSUSE/opennebula.sudoers

The actual sudo configuration apply globally and can conflict with
system configuration.
* share/pkgs/CentOS/opennebula.sudoers: Limit the “!requiretty” and
“secure_path” to user oneadmin.
* share/pkgs/Debian/opennebula.sudoers: Ditoo.
* share/pkgs/Ubuntu/opennebula.sudoers: Ditoo.
* share/pkgs/openSUSE/opennebula.sudoers: Ditoo.

Do not override global sudo configuration

---

share/install_gems/install_gems

This PR includes 2 new options into install_gems script:
* --showallpackages: to show the list of packages required to compile the gems.
* --showallgems: to show the complete list of required gems.
These new options may be useful for external utils  and addons to generate rpm or deb packages for example.

install_gems: included new options to show pkgs and gems list

---

src/cli/one_helper/oneimage_helper.rb

When running "oneimage create --path .." the tool should check not only
for the existence but also for the readability of the given image.
If the image is unreadable (one user create the image an other tries to
upload it) the image will be created in ERROR state in the datastore.
Best wishes,
Matthias

Check if an given image is readable in oneimage.

---

src/cli/oneimage

The command shows how to create a new image using a path to the image
so the comment should reflect that. I guess the removed words "of type centOS" are ether a copy & paste mistake or it should state that the default type of an image is OS. But this should better be documented whithin the "## OPTIONS" section. 
Should i open a pull-request with added documentation about the cli parameter defaults? 
best wishes,
Matthias

Remove possible copy&paste mistake

---

src/pool/PoolObjectSQL.cc

To confirm, run Michael's test script. Tested using the 4.12.0 OpenNebula sandbox.

Bug #3829 Memory leak in onehost update - added missing delete

---

src/sunstone/etc/sunstone-views/admin.yaml
src/sunstone/etc/sunstone-views/admin_vcenter.yaml
src/sunstone/etc/sunstone-views/user.yaml

See Bug #3844: http://dev.opennebula.org/issues/3844
src/sunstone/public/js/plugins/groups-tab.js expects 'showback'.

fixed typo 'shoback'=>'showback'

---

src/vnm_mad/remotes/lib/sg_driver.rb

When a NIC is attached, we only try to add security group associated to that NIC.

Bug #3846: Already existing rules in security group driver

---

src/authm_mad/remotes/ldap/ldap_auth.rb

Users should only be added to the default group if it's defined and the user's groups aren't mapped (ie get_groups() is empty). This is correctly handled by the `remotes/auth/ldap/authenticate` script by checking whether or not get_groups returns an empty list.

fix default group bug in get_groups()

---

src/tm_mad/common/context

While digging another issue, I've spot that when there is SYSTEM_DS migration (at least on the shared TM_MAD) the symlink became broken because it is pointing to the absolute path, which is not available after the migration.
The proposed patch is creating the symlink relative so there is no issue when the absolute path is changed.
The patch is against current master branch but the issue exists in the current stable (4.14.2) too.

fix ISO symlink for VMware CDROMs

---

src/vnm_mad/remotes/lib/security_groups_iptables.rb

Don't filter UDP DHCP traffic from 0.0.0.0/32 port 68 to
255.255.255.255/32 port 67.

Bug #4337: IP spoofing filters DHCP communication

---

src/cloud/ec2/lib/elastic_ip.rb

The current code in `ElasticIP::associate_address()` strips the leading `i-` prefix of VM instance IDs, if found, in order to convert EC2 instance IDs into OpenNebula VM IDs. Unfortunately that does not work for IDs greater than 7, since the stripped string is interpreted as an octal number due to the remaining leading 0's:
$ econe-allocate-address
$ econe-describe-addresses 
publicIp                instanceId
192.168.1.
$ econe-associate-address 192.168.1.1 i-00000106
$ econe-describe-addresses 
publicIp                instanceId
192.168.1.                i-00000070 
(Note that decimal 106 is octal 70)

Fix VM ID parsing in `associate_address()`

---

src/cloud/ec2/bin/econe-describe-addresses

The current with of the IP address column is too small: The IP address "192.168.1.64", for instance, is 12 characters long, and gets truncated to "192.168.1.". Reserving 15 should do:
irb(main):001:0> "XXX.XXX.XXX.XXX".length
=> 15
irb(main):002:0>

Fix output of `econe-describe-addresses`

---

src/scheduler/etc/sched.conf
src/scheduler/include/Scheduler.h
src/scheduler/src/sched/Scheduler.cc

http://dev.opennebula.org/issues/4404

Feature #4404: Add ONE_XMLRPC attribute in the scheduler configuration file

---

src/cloud/common/CloudAuth/EC2CloudAuth.rb

Econe server fails with 
```
<NoMethodError: undefined method `split' for nil:NilClass>
```
when using some clients (ec2 Ansible modules for example). The problem
lies in parsing Authentication header format.
Euca sends:
```
Credential=tom/20160425/undefined-19606/ec2/aws4_request, SignedHeaders=accept;accept-encoding;connection;content-length;content-type;host;x-amz-content-sha256;x-amz-date, Signature=fsomehash8cda2
```
Ansible EC2 module sends:
```
Credential=tom/20160425/servers/one/aws4_request,SignedHeaders=host;x-amz-date,Signature=6b2ccdsomehash39f2fc555
```
Previous implementation fails when fields are separated with "," (without space). Documentation [1] for AWS API says "are separated by a comma" so there should be just comma, but I'd prefer to maintain compatibility with euca …

fix parsing of Authorization header

---

src/im_mad/remotes/kvm-probes.d/kvm.rb

The LANG environment variable does not work as expected with virsh -c qemu:///system nodeinfo. But LC_ALL=C works fine.
Without LC_ALL=C monitoring fails with a "Error monitoring Host hostname (0): ./kvm.rb:49: undefined method `*' for nil:NilClass (NoMethodError)".
Server configuration:
OS: CentOS 6.2
OpenNebula: 4.14.2
Default language: ru_RU.UTF-8
Bug example:
LANG=C virsh -c qemu:///system nodeinfo
Модель процессора: x86_64
CPU:                 16
Частота процессора: 1600 MHz
Сокеты:        1
Ядер на сокет: 4
Потоков на ядро: 2
Ячейки NUMA:   2
Объём памяти: 74237932 KiB
Correct behavior:
LC_ALL=C virsh -c qemu:///system nodeinfo
CPU model:           x86_64
CPU(s):              16
CPU frequency:       1600 MHz
CPU socket(s):       1
Core(s) per socket:  4
Thread(s) per core:  2
NUMA …

Update kvm.rb to fix localization bug

---

src/vm/VirtualMachine.cc

This is to make sure that the ORDER attribute is removed correctly for disks and nics if we remove OS = [ BOOT = "disk0,...." ] from the XML template of the VM.

Remove orders attributes when removing boot orders

---

src/datastore_mad/remotes/ceph/monitor

This is related to Backlog #3953. There is a bug  with the current text output parsing of "ceph df". The grep command is considering pool names composed with a dash "-" as multiple words. Even when using "grep -w".
As a consequence, 
`echo -e "one\none-123\none-test" | grep one`
or
`echo -e "one\none-123\none-test" | grep -w one`
will match the three pools.
The proposed solution is to parse XML output of "ceph df" instead of text output.

Backlog #3953: "ceph df" XML output parsing for the monitor script

---

src/lcm/LifeCycleStates.cc

Hi Developers,
http://dev.opennebula.org/issues/4593
When VM in UNKNOWN state is rescheduled it can not be migrated anymore because a check in VirtualMachineMigrate::request_execute is not satisfied due to previous history record not closed properly.
https://github.com/OpenNebula/one/blob/master/src/rm/RequestManagerVirtualMachine.cc#L1097
The suggested patch updates(closes) previous history record properly (I hope) and the VM is in proper state then.
Kind Regards,
Anton Todorov

fix for bug #4593

---

src/tm_mad/ssh/mv

Following https://forum.opennebula.org/t/vm-fails-to-ha-reschedule-on-host-error-opennebula-5-0-1/2566
Skip access to the source host when called in LCM_STATE=PROLOG_MIGRATE_UNKNOWN because the source host is not reachable.
It is used in CEPH's TM_MAD but I think it is OK for SSH too.

fix for FT action when host is in ERROR state

---

src/vm/VirtualMachine.cc
src/vmm/LibVirtDriverKVM.cc

* src/vm/VirtualMachine.cc (insert): Add “EMULATOR” to the list of
VM attributes understood by opennebula.
* src/vmm/LibVirtDriverKVM.cc (deployment_description_kvm): Get
“EMULATOR” from VM template first, then from default and finally from
hardcoded path.
Thanks Vladislav Gorbunov for the patch

Feature #3510: authorize “EMULATOR” in VM TEMPLATE

---

src/sunstone/public/app/utils/vcenter/templates.js

WARNING: "All %1$s Templates selected." and "%1$s Templates selected." should be added to messages so they can be translated in Transifex. I'm not sure how to do that so I won't be editing that locale files.

Fix typo. Networks should be Templates

---

src/datastore_mad/remotes/vcenter/cp

- Uploading standalone vmdk file (uncompressed) looses vmdk file extension so vCenter can't browse it. Now a vmdk extension is added.
Uploading standalone vmdk file compressed with GZIP or BZIP2 changes file name to folder hash. Now a human readable name based on the original name and extension is added so it can be browsed.

B #4687: Uploading gzip files with no tar in vcenter DS should fail gracefully

---

src/tm_mad/qcow2/clone

Following this forum thread
https://forum.opennebula.org/t/opennebula-5-0-2-attach-detach-images-datastore-folder-not-cleaned-up/3111
Please let me know if you need it backported to 5.0.2 too

fix issue when cloning qcow2 images

---

src/tm_mad/common/delete

following this forum thread
https://forum.opennebula.org/t/opennebula-5-0-2-attach-detach-images-datastore-folder-not-cleaned-up/3111

fix deleting qcow2 images

---

src/vnm_mad/remotes/lib/vnmmad.rb

On hypervisor, scripts are located inside /var/tmp/one/vnm directory but executed from /var/lib/one directory and therefore, file require with relative path isn't working.

vnm_mad: Use absolute instead of relative path to require scripts in vnmmad-load.d directory

---

src/cloud/ec2/lib/EC2QueryServer.rb

By forcing the date to utc the xmlscheme function will return the date format expected by aws java sdk.
This works in my tests but i am not sure if it has impact to any other integration. As aws uses utc/zulu time stamps in every case it should be fine but i do not have enough insight into other integrations.

Fix for http://dev.opennebula.org/issues/4656

---

src/vmm_mad/remotes/vcenter/vcenter_driver.rb

Remove the problematic nic.elements["BRIDGE"].text == dv.deviceInfo.summary which could duplicate NICs in certain circumstances.

Fix duplicated NICs issue

---

src/vmm_mad/remotes/vcenter/vcenter_driver.rb

A new variable is used in the extraConfig section of a VM and it's called opennebula.hotplugged_nics 
That variable is used to track the mac addresses of those NICs that have been hot-plugged to that VM. If a VM has a hot-plugged NIC and goes to the POWEROFF state, if that NIC is detached in that state it's only removed from the XML file and it remains in vCenter.
To solve this issue, I check if there are MAC addresses in vCenter which are not inside the XML. I could remove all NICs from vCenter which were not in the XML but as OpenNebula can't see the NICs that are inside a template when it's imported, it could remove accidently those "invisible" NICs. The only way I've found acceptable is the use of extraConfig with the variable opennebula.hotplugged_nics. That way I can know which MAC …

Fix B4897 NIC is not removed from vCenter if you detach a NIC when in POWEROFF

---

install.sh
src/cli/onevcenter
src/datastore_mad/remotes/vcenter_downloader.rb
src/datastore_mad/remotes/vcenter_uploader.rb
src/vmm_mad/remotes/vcenter/vcenter_driver.rb

Now the StorageDRS cluster can be used to deploy (clone) a VM. StorageDRS is imported as SYSTEM DS so images can't be uploaded to it.

F5484 Enhance StorageDRS allowing VM deployment

---

src/vmm_mad/remotes/vcenter/vcenter_driver.rb

Also do not create duplicates if network is present in several hosts in a cluster.

Fix B#4928 import vcenter networks with same name in different clusters

---

src/vmm_mad/remotes/vcenter/vcenter_driver.rb

Negative values are not processed. Negative values mean that PerfomanceManager doesn't consider them valid.
A LAST_MON element is used in the MONITORING section to track when was the last time the information was requested so it helps to calculate how many 20 seconds samples are queried to the PerformanceManager.
The following metrics are used: 'net.transmitted','net.bytesRx','net.bytesTx','net.received'. Max value between net.transmitted and net.bytesTx is used as the transmitted bytes (same for reception).
Current NETTX and NETRX are sumed to last monitored values so they are accumulated.

Fix NETTX and NETRX negative values, polling time and accumulate values

---

src/sunstone/etc/sunstone-server.conf
src/sunstone/sunstone-server.rb

exposed the sunstone session timeout so that it can be set in sunstone-server.conf

sunstone-server.conf session length parameter

---

share/install_gems/Ubuntu1610/Gemfile.lock
share/install_gems/install_gems

Changes:
* Install all Gems dependencies when using bundler (cc: @jfontan)
* New Gemfile.lock for Ubuntu 16.10

Install all Gems deps when using bundler. Ubuntu 16.10 Gemfile.lock

---

include/Log.h
src/log/Log.cc

For the centralized syslog project I'm working on I've noted that the program name field was missing:
> Feb  6 10:01:19 one-sandbox [4217]: [Z0][AuM][I]: #011Auth Manager loaded
> Feb  6 10:01:19 one-sandbox [4217]: [Z0][ReM][I]: Starting Request Manager...
> Feb  6 10:01:19 one-sandbox [4217]: [Z0][ReM][I]: Starting XML-RPC server, port 2633 ...
> Feb  6 10:01:19 one-sandbox [4217]: [Z0][ReM][I]: Request Manager started.
After my modification:
> Feb  7 06:49:05 one-sandbox oned[29752]: [Z0][AuM][I]: #011Auth Manager loaded
> Feb  7 06:49:05 one-sandbox oned[29752]: [Z0][ReM][I]: Starting Request Manager...
> Feb  7 06:49:05 one-sandbox oned[29752]: [Z0][ReM][I]: Starting XML-RPC server, port 2633 ...
> Feb  7 06:49:05 one-sandbox oned[29752]: [Z0][ReM][I]: Request Manager started. …

Fix: Missing programname in syslog output

---

share/pkgs/CentOS7/opennebula.service

References https://github.com/OpenNebula/docs/pull/93
On Debian-like systems, the MariaDB service name is still **mysql**. This small change adds soft dependency also on *mysql.service* into the systemd service script.

Add OpenNebula systemd service dependency on MySQL

---

src/datastore_mad/remotes/fs/snap_delete
src/datastore_mad/remotes/fs/snap_flatten
src/datastore_mad/remotes/fs/snap_revert

The PR includes also changes from PR #298 (by @feldsam). Fixes fs/snap_* for:
1. BRIDGE_LIST, support was missing
2. loss of the particular snapshot on revert (both qcow2/non-qcow2)

Bug 5144 - fs/snap_* BRIDGE_LIST, fixes

---

src/cli/one_helper.rb
src/cli/onehost
src/vmm_mad/remotes/ec2/ec2_driver.rb

* Bug 5012
it's possible to see live mem values
* Tags_bug
ec2 drivers was failing when you try to get instantiate a template without any tags, now is solved.
Feature 5136:
Now it's mandatory to add authentication ec2 options in --ec2access --ec2secret parameters instead of ec2_driver.conf
```
$  onehost create ec2-test --im ec2 --vm ec2 --ec2access accessloginhash --ec2secret ec2secrethash
```

Feature 5136 && Bug 5012

---

src/vmm_mad/remotes/kvm/migrate
src/vmm_mad/remotes/kvm/migrate_local

Otherwise the migration fails on existing snapshots:
"error: Requested operation is not valid: cannot migrate domain with 3 snapshots"

B #5145: Drop domain snapshots before live-migrate

---

src/onedb/database_schema.rb

'sql' is reserved word in MariaDB

F #4809: rename sql to sqlcmd in database_schema.rb

---

src/tm_mad/ceph/resize

This allows to resize a ceph persistent disk by getting its name from
the SOURCE parameter on the disk in the VM template. (If PERSISTENT is
not YES, the behavior is as before.)

fix ceph tm_mad to allow resizing persistent disk

---

src/vmm/LibVirtDriverKVM.cc

This adds VROUTER_IP, if present, to the libvirt network filter; without
this any traffic from the vrouter IP is blocked by ebtables if using the
libvirt network filter.
Fixes B 5109 https://dev.opennebula.org/issues/5109

B #5109 fix libvirt network filter for vrouter IPs

---

src/datastore_mad/remotes/fs/snap_revert
src/tm_mad/qcow2/clone
src/tm_mad/qcow2/snap_create
src/tm_mad/qcow2/snap_create_live
src/tm_mad/qcow2/snap_revert

Fixes the AppArmor file access denies in most cases, except hot-attach of the nonpersistent disk (https://bugzilla.redhat.com/show_bug.cgi?id=1361592).

B #5035: Specify QCOW2 backing file formats

---

src/datastore_mad/remotes/xpath.rb

by returning empty string.
Handling both `<test/>` and `<test></test>`
test pattern:
```
echo -e "<A>\n<B>b</B>\n<C/>\n<D></D><E>e</E></A>\n"| /var/lib/one/remotes/datastore/xpath.rb /A/B /A/C /A/D /A/E | while IFS= read -r -d '' e; do echo "'$e'"; done
```

xpath.rb fix crash when querying empty-element tag

---

src/vnm_mad/remotes/vxlan/vxlan_driver.rb

Since the upgrade to opennebula 5.4, the creation of vxlan doesn't work.
In the commit fe84d376acb079c1c1a357e9e69834fcbba2502d the module `VNMMAD::VNMNetwork::IPv4` has been removed and `IPAddr` class used.
But on merge 1b28fbe354f84177ac46065d7fb22c880e288127 `VNMMAD::VNMNetwork::IPv4` is used again but without the module declaration in `lib/address.rb`

Fix vxlan device creation

---

src/authm_mad/remotes/ldap/ldap_auth.rb

ldap uses base64 encoding iff there are non-ascii chars.
For some reason the query seems to then return the user_group_name
(src/authm_mad/remotes/ldap/authenticate) as ascii-encoded.
This is only relevant when a group is set in ldap_auth.conf, in which
case ldap.is_in_group is called.
By forcing the encoding to utf-8 the authentication succeeds.
Before this error was encountered:
Exception raised authenticating to LDAP
(UTF-8 regexp with ASCII-8BIT string)>
/usr/lib/ruby/vendor_ruby/net/ldap/filter.rb:755:in `scan'
/usr/lib/ruby/vendor_ruby/net/ldap/filter.rb:755:in
`parse_filter_branch'
/usr/lib/ruby/vendor_ruby/net/ldap/filter.rb:737:in
`parse_paren_expression'
/usr/lib/ruby/vendor_ruby/net/ldap/filter.rb:682:in `parse'
/usr/lib/ruby/vendor_ruby/net/ldap/filter.rb:673:in `initialize' …

Fix authentication for users with non-ascii chars in their names

---

src/authm_mad/remotes/ldap/ldap_auth.rb

This change will allow user_field to contain characters such as `;`. This is useful because some of ldap attributes look like `login;organization`.

Ldap filter can use `;` character

---

src/vmm_mad/remotes/kvm/snapshot_create

libvirt/QEMU has problem with simple numberic names,
it's confused with the internal snapshot IDs:
https://bugzilla.redhat.com/show_bug.cgi?id=733143

B #5393: Prefix libvirt snapshot name with snap-

---

src/sunstone/public/app/tabs/hosts-tab/panels/info.js

- Prevent multiple events.
- "Update" button disabled while the ajax request lasts.
- JS selectors changed by jQuery selectors.

B #5390: Prevent multiple clicks events in overcommitment (host tab)

---

src/datastore_mad/remotes/common/stat
src/datastore_mad/remotes/downloader.sh
src/datastore_mad/remotes/libfs.sh
src/tm_mad/fs_lvm/clone

Improves support for importing of the compressed images, except the remote compressed raw images (these require complete image download to get the size). Adds XZ support.
format / compression | no | .gz | .bz2 | .xz
------|--------|-----|------|------
raw | OK | - | - | -
qcow2 | OK | OK | OK | OK
vmdk | OK | OK | OK | OK
format / compression | no | .gz | .bz2 | .xz
------|--------|-----|------|------
raw | OK | OK | OK | OK
qcow2 | OK | OK | OK | OK
vmdk | OK | OK | OK | OK

B #1481: Better estimate image sizes

---

src/tm_mad/ceph/snap_revert

For setups with multiple Ceph clusters we introduced the "CEPH_KEY" variable a while ago. All CEPH drivers have this CEPH_KEY, but snap_revert did not use it yet. This PR to fix that.

Add CEPH_KEY to snap_revert driver operation

---

src/rm/RequestManagerUser.cc

Hello,
this pull request adds one more check before token creation. It checks if token that was used to generate another token has access to requested groups. In practice that means that users with token just for group 100 cannot create token for group 0 and so on. Also tokens scoped for group cannot be used to generate token for all groups that user belongs to (to generate unscoped token).
I hope this explains the issue. Also if any part of my pull request should be changed let me know and I will do my best.

Fix token creation handeling

---

src/sunstone/routes/support.rb

Tested today towards zendesk and severity was not submitted correctly. I figure out, that we need to add severity value to tags also, because dropdown custom field use tags at the background.
Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

Fixed create support ticket severity custom field

---

src/vnm_mad/remotes/ovswitch/OpenvSwitch.rb

Trivial fix concerning feature #1865 
Tested for ex with VLAN_TAGGED_ID=42,300-400,500 and get 
`trunks              : [42, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 500]`

Allow vlan range notation in ovs

---

src/im_mad/remotes/kvm-probes.d/cpu.sh

This minor adjustment allows the detection of PPC CPUs by the standard KVM driver.
I have 2 POWER8 machines that i use as KVM host with this change in place.
The only thing needed besides that is a correct node selection and the definition of EMULATOR in the VM template

Add support for PowerPC CPUs

---

src/cli/etc/onehost.yaml
src/oca/ruby/opennebula/host.rb

flush <range|hostid_list>
Disables the host and reschedules all the running VMs in it.
-h, --help                Show this message
-V, --version             Show version and copyright information
--user name               User name used to connect to OpenNebula
--password password       Password to authenticate with OpenNebula
--endpoint endpoint       URL of OpenNebula xmlrpc frontend command more configurable

F#2153 Do Command flush requires one parameter to run

---

src/sunstone/etc/sunstone-server.conf
src/sunstone/public/app/sunstone-config.js

> Actually we have the @websocketproxy.py@ listening on the port @29876@ and the NoVNC client open a WebSocket directly on that port.
> I would like the client to only use the port @443@ as I already have a nginx reverse proxy.
**N.B: this a quick fix but this modification doesn't introduce any breaking change. It could be refactored later or pulled out and replaced with a true fix for the next major release.**
In addition to the diff within this PR, this configuration should allow the web client to connect through a reverse proxy on `:443` .
* /etc/one/sunstone-server.conf
```yaml
:vnc_proxy_port: 127.0.0.1:29876
:vnc_proxy_support_wss: yes
:vnc_proxy_cert: /etc/pki/nginx/sunstone.crt
:vnc_proxy_key: /etc/pki/nginx/private/sunstone.key
:vnc_proxy_ipv6: false
:vnc_request_password: false …
```

[#878] Allow the VNC JS WS client to connect to a different port than :vnc_proxy_port

---

src/tm_mad/fs_lvm/postmigrate
src/tm_mad/fs_lvm/premigrate

**Description**
Can't live migrate VM if it have connected storage disks from the `shared` datastore eg CD-ROMS (not `fs_lvm`)
**To Reproduce**
- Connect shared cd-rom image to the lvm backed vm
- try to live-migrate it.
**Actual behavior**
```
...
[Z0][VMM][I]: + for disk in $(ls /var/lib/one//datastores/164/6237/disk.*)
[Z0][VMM][I]: + '[' -L /var/lib/one//datastores/164/6237/disk.3 ']'
[Z0][VMM][I]: ++ readlink /var/lib/one//datastores/164/6237/disk.3
[Z0][VMM][I]: + DEVICE=/var/lib/one/datastores/100/805cba38656802399588f09cd8958010
[Z0][VMM][I]: + sudo lvchange -ay /var/lib/one/datastores/100/805cba38656802399588f09cd8958010
[Z0][VMM][I]: "/var/lib/one/datastores/100/805cba38656802399588f09cd8958010": Invalid path for Logical Volume.
```
**Expected behavior**
VM successfully migrated …

Fix: fs_lvm live migration

---

src/sunstone/views/index.erb

This wires up the javascript client to use the configured vnc_client_port.
---
Adding this allowed us to wire up vnc without adding additional firewall rules to our lb.

Pass vnc_client_port into javascript

---

src/cli/one_helper/onevcenter_helper.rb
src/cli/onevcenter

B #2416: onevcenter tool improvements and fixes

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

B #2433 Monitoring VMs fails when there is not datastore associated

---

src/oca/go/src/goca/image.go

This commit adds the following call in image.go:
* clone
* enable
* persistent
* chtype
* update
* chmod
* chown
* rename
* snapshotdelete
* snapshotrevert
* snapshotflatten
* lock
* unlock

B #2576: Add missing XML RPC call for image GO bindings

---

src/vmm_mad/remotes/lib/lxd/svncterm_server/SConstruct
src/vmm_mad/remotes/lib/lxd/svncterm_server/genfont.c

in addition `libvncserver-devel` should be installed to build on CentOS7

F#1684: Fix building svncterm server for LxD

---

src/oca/go/src/goca/goca.go

I submit a branch with two commit:
The first providing a way to fix an error
The second suggesting to replace remaining fatal calls with specialized errors
The main effect is to allow errors handling in a better way with type assertion, and to avoid goca to kill the main program

B #2678: GOCA - fix and modify xmlrpc client error checking

---

src/oca/go/src/goca/image.go

This pull request add a missing value for the state attribute.
It's documented and the corresponding string is present in sources so it's probably a mistake.

B #2674: GOCA - fix missing state value of image

---

src/oca/go/src/goca/host.go

This pull request add values and string for the state of the hosts in goca
It's documented in the XMLRPC api and I just propose to add corresponding the code.
It's implemented for others elements as VM, images ...

F #2662: GOCA - Add host state values and strings

---

src/datastore_mad/remotes/ceph/snap_revert
src/tm_mad/ceph/snap_revert

Hi, I fixed the bug I've posted before.
Please review and merge if the fix is ok :)

F #2476: Erasure-coded Ceph VM images forget about being erasure-coded after restoring a snapshot

---

src/oca/go/src/goca/errors.go
src/oca/go/src/goca/goca.go

This pull request contain two commit:
The first one leverage the use of the current xmlrpc package replacing the current client with the client from the net/http package
The second commit adapt the error handling and add more of error cases

F #2772: GOCA - leverage use of current xmlrpc package and update error handling

---

src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lib/lxd/mapper/mapper.rb
src/vmm_mad/remotes/lib/lxd/mapper/raw.rb

* add '-s' to the _file_ command to read special devices
* add '-s' to enable "sync mode" _kpartx_ when adding partition mappings
and handle the DISK case for disk['TYPE']

F #1684 handle disk TYPE=BLOCK for LxD containers

---

src/vmm_mad/remotes/lxd/poll

* handle exceptions in get_memory()
* add option to set cgroup prefix to the container path via the environment variable `LXC_CGROUP_PREFIX`
In case of a more complex cgroup configuration the containers cgroup could be placed in separate slice instead of default root cgroup. In this case the defining LXC_CGROUP_PREFIX="system.slice/" (note the trailing slash) in the environment will help vmm/lxd/poll to construct correct path the needed *memory* and *cpu,cpuacct* cgroups
```bash
su - oneadmin -c 'echo "export LXC_CGROUP_PREFIX=system.slice" >>~/.bashrc'
```

B #2824 fix LXD container monitoring

---

src/vmm_mad/remotes/lib/lxd/mapper/qcow2.rb

Not using `kpartx -d` on a multipart image on 1604 caused next single part image to have ghosts partition mappings, remnants of the previous image.

F #1684: Fix multipart nbd causing issue on next single part image

---

src/cli/one_helper/onehost_helper.rb
src/im_mad/im_exec/one_im_exec.rb
src/mad/ruby/CommandManager.rb

OpenNebula was failing to enlist a new host. I made this change and restarted the nebula services and the host was then enlisted correctly.
```
Fri Feb  8 15:04:34 2019 [Z0][InM][I]: Command execution failed (exit code: 1): scp -rp /var/lib/one/remotes/. sd-prod-kvm1106:/var/tmp/one
Fri Feb  8 15:04:34 2019 [Z0][InM][I]: scp: error: unexpected filename: .
```
I was also able to reproduce this from the command line:
```
oneadmin@sd-prod-nebula1:~$ scp -rp /var/lib/one/remotes/. sd-prod-kvm1106:/var/tmp/one
scp: error: unexpected filename: .
```

Fix "scp: error: unexpected filename: ."

---

src/datastore_mad/remotes/ceph/ceph_utils.sh
src/datastore_mad/remotes/ceph/monitor

Adjust ceph monitor / ceph_utils so that if there is a quota on the pool this value gets used (if it is lower than max_avail) to calculate capacity
(Applied from https://github.com/OpenNebula/one/pull/127 which I closed by mistake)

Adjust ceph monitor if there is a quota

---

src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lxd/reboot

Unlike libvirt which handles the ports removal on nic detach action nad powerofss, LXD just handles nic port creation on start and nic attach. The drivers have been updated to remove ports on unhandled actions if nic matches ovswitch driver.
Fixes #3058

Fix LXD not handling nic removal from openvswitch bridges

---

src/vmm_mad/remotes/lib/lxd/container.rb

the log is embedded into `wait?` method, so the rest of the containers methods benefit from it

F #3099 Show container log when action fails

---

src/vnm_mad/remotes/lib/vnm_driver.rb

It could either be relocate the method like this or append the class to https://github.com/OpenNebula/one/blob/308d304851a2fd86eec7a1ec20f7e07efcb9dc9d/src/vnm_mad/remotes/lib/vm.rb#L48
Error is as follows
```
Tue Mar 26 06:38:28 2019 [Z0][VMM][I]: Command execution fail: /var/tmp/one/vnm/fw/pre PFZNPjxJRD4yMDwvSUQ+PERFUExPWV9JRC8+PFRFTVBMQVRFPjxDT05URVhUPjxESVNLX0lEPjwhW0NEQVRBWzFdXT48L0RJU0tfSUQ+PEVUSDBfQ09OVEVYVF9GT1JDRV9JUFY0PjwhW0NEQVRBW11dPjwvRVRIMF9DT05URVhUX0ZPUkNFX0lQVjQ+PEVUSDBfRE5TPjwhW0NEQVRBW11dPjwvRVRIMF9ETlM+PEVUSDBfRVhURVJOQUw+PCFbQ0RBVEFbXV0+PC9FVEgwX0VYVEVSTkFMPjxFVEgwX0dBVEVXQVk+PCFbQ0RBVEFbMTkyLjE2OC4xNTAuMV1dPjwvRVRIMF9HQVRFV0FZPjxFVEgwX0dBVEVXQVk2PjwhW0NEQVRBW11dPjwvRVRIMF9HQVRFV0FZNj48RVRIMF9JUD48IVtDREFUQVsxOTIuMTY4LjE1MC4xMDBdXT48L0VUSDBfSVA+PEVUSDBfSVA2PjwhW0NEQVR …
```

Move pre_action into VMMAD module

---

src/vmm_mad/remotes/lib/lxd/mapper/mapper.rb

Another follow up to #3127 
Removed the mapper execution based on the status of this part of the code. 1604 fails  and fails both `e2fsck` and `tune2fs`. If that fails the code will handle it later

B #3127 Remove status handling from filesystem code

---

src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lxd/reboot
src/vmm_mad/remotes/lxd/shutdown
src/vnm_mad/remotes/lib/nic.rb

- A simple check that helps with non opennebula managed shutdown operations (lxc stops, container inner poweroffs, sudden shutdowns)
- Sometimes we just need space

LXD Follow-up fixes

---

src/oca/go/src/goca/goca.go

An http response was missing, and some errors were in fact to nil

B #2678 GOCA - fix and clarify client errors

---

src/datastore_mad/remotes/lxd_downloader.sh

Replaces #3138 
- centos 6 and 7 enable sshd at startup after installing openssh-server
- alpine was missing curl, so it couldn't get the context package
- packages were being left on container `/root/` directory
Since we won't add ssh dependency for alpine on context-package, we could install openssh here on alpine case.

Fix LXD market importer

---

src/datastore_mad/remotes/lxd_downloader.sh

enabling sshd on alpine during chroot was failing.
Merge for 5.8.1

F #3164 Fix LXD marketplace imape importer with alpine

---

src/vmm_mad/remotes/lib/lxd/mapper/qcow2.rb

Use modprobe -c to load max number of nbd devices
Closes #3177

B #3177 Load max_nbds from running module

---

src/vmm_mad/remotes/lxd/shutdown

Shutting down wild containers was yieling: 
```
`<main>': unexpected return (LocalJumpError)
```

B #3175 use exit 0 instead of return

---

src/tm_mad/fs_lvm/delete
src/tm_mad/fs_lvm/mv

**Note for reviewer:**
This PR includes the next fixes:
1) Remove check for `/VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/TYPE` solves problem with offline and datastore migration. fixes #2359 and #3130. Add check for `LCM_STATE` instead, fs_lvm driver now correctly disables logical volume during undeploy VM.
2) Fix directory cleanup during termination undeployed VM for storage with the `BRIDGE_LIST` variable set. The expression for finding `DS_SYS_ID` was never work if `DST_PATH` is directory. fixes https://github.com/OpenNebula/one/issues/2981#issuecomment-478632787 and #2352 
5) Fix when node in `BRIDGE_LIST` have no activated lvm device, so zeroing is not working. Now it will always activate the device before zeroing.

 F #2352 #2359 #2981 #3130 #3233: Fix fs_lvm cleanup and offline migration issues

---

src/tm_mad/fs_lvm/mv

Fix recovering from the STOPPED state on the fronted

B #3246: Don't deactivate LV also for `PROLOG_RESUME` operation

---

src/vnm_mad/remotes/ovswitch/OpenvSwitch.rb

The “del_flows” override the loop variable “m” when matching the port,
on the second loop which result in the following error.
/var/tmp/one/vnm/ovswitch/OpenvSwitch.rb:287:in `match': wrong argument type MatchData (expected Regexp) (TypeError)
* src/vnm_mad/remotes/ovswitch/OpenvSwitch.rb (OpenvSwitchVLAN#del_flows):
use two different variables

OpenvSwitch “del_flows” override loop variables

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #964: Allow FILES_DS for vCenter

---

src/oca/ruby/opennebula/pool.rb
src/onedb/onedb
src/onedb/onedb_live.rb

* Process done VMs in pages, instead of all together
* Add new method to iterate over pages
* Add new CLI paramter to specify pages size

B #3269: onedb purge-done eat too much RAM

---

src/onedb/fsck/quotas.rb

B #1710: fix bug when parent_id is empty

---

src/cli/one_helper/onezone_helper.rb

F #3378: add new column to show fed index

---

src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lxd/reconfigure

Reconfigure now runs recontextualization through REST API, simply post and don't verify nor wait for result.
We cannot get rid of snap hacks yet since we still need exec through CLI for svncterm  :(
Hopefully this and #3406 will solve https://github.com/OpenNebula/one/issues/3390 and https://github.com/OpenNebula/one/issues/3389

Update recontextualization execution

---

src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lxd/poll

Doesn't cover wild containers, but since the time they are stopped is minimal compared to full fledged containers, IMHO it isn't necessary.

B #3389: Add pre_boot status

---

src/vnm_mad/remotes/lib/security_groups_iptables.rb
src/vnm_mad/remotes/lib/vm.rb

- src/vnm_mad/remotes/lib/vm.rb:
add array of NIC aliases to the nic Array
- src/vnm_mad/remotes/lib/security_groups_iptables.rb:
update ipv4s(and ipv6s) with the alias ips

B #3354: add NIC aliases to the IP spoofing filter

---

src/datastore_mad/remotes/lxd_downloader.sh

Added devuan and fedora.
Fedora 30 still fails on hostname context though. See https://github.com/OpenNebula/one/issues/3178#issuecomment-509506277

Update auto-context apps on LXD market

---

src/vmm_mad/exec/one_vmm_exec.rb

I believe the deploy_id isn't generated after the deploy action fails. So the cleanup action check skips the net clean steps. When vnm post fails the `deploy_id` is indeed generated and the vm cleanup runs successfully the network cleanup. 
I just moved the net clean outside of the check.
- Fixes #3540
- Applies to one-5.8 as well.
- [Doc PR](https://github.com/OpenNebula/docs/pull/709)

B #3540: Ensure vnm clean

---

src/oca/go/src/goca/go.mod
src/oca/go/src/goca/go.sum

F #3227: GOCA: update dependencies

---

src/oca/go/src/goca/vm.go

Returns the image ID from the saveas method

B #3616: GOCA - fix saveas method mapping

---

src/vnm_mad/remotes/lib/sg_driver.rb

Activates and deactivates methods in this class weren't returning 0 when successful, unlike other drivers classes.
Fixes #3510 
Doesn't apply to one-5.8

B #3510: Fix 802.1Q hooks

---

src/vnm_mad/remotes/lib/security_groups_iptables.rb
src/vnm_mad/remotes/lib/vnm_driver.rb

Closes #3509 
By default stdout is logged, stderr is logged when custom script fails to run.

Log vnm hooks output

---

src/vnm_mad/remotes/dummy/clean
src/vnm_mad/remotes/dummy/post
src/vnm_mad/remotes/dummy/pre

File path was being wrong on execution.
```
.//var/tmp/one/vnm/dummy/pre.d/01_ruby1: No such file or directory
```

F #2451 Fix dummy vnm hoks

---

src/vnm_mad/remotes/lib/nic.rb

Updated the LXD snap-based setup detection mechanism on the network drivers.It seems `snapd` got updated and error output changed to
```
oneadmin@ubuntu1810-lxd-qcow2-0f30a-1:~$ lxc list
Sorry, home directories outside of /home are not currently supported. 
See https://forum.snapcraft.io/t/11209 for details.
```
Code doesn't require that output to be checked now
- Applies to master as well
- Closes #3596

Lxd snap update

---

src/vmm_mad/remotes/lib/nsx_driver/nsx_client.rb
src/vmm_mad/remotes/lib/vcenter_driver/host.rb

Fix a monitoring loop that occurs when NSX Manager is not
reachable. An SSH exception is created an created a personalized
message that break the format of the attribute NSX_STATUS.
That message has been changed to a static message.
Also fix a typo when launching an Standard Error.

F #3440: Fix monitoring loop

---

src/vnm_mad/remotes/lib/vlan.rb

Command `ip link show master br_name` list attached vlan devices with @master_dev on el8 systems. For example `team0.404@team0`. This commit fixes parsing bridges and attached devices.
Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

F #3613: Fixed vlan driver on el8 systems

---

src/market_mad/remotes/linuxcontainers/monitor

"Original" values for the `security.privileged` container configuration key were `true/false`, so had the monitor script followed. However, the template wizard looks for [yes/no](https://github.com/OpenNebula/one/blob/424028d19c0607445be484e0f32e8cf3c0f2f25a/src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/general/html.hbs#L121-L122) and these two parts of opennebula not with the same value led to #3559.
- Applies to one-5.8 and master
- Fixes #3559
- Added a possible feature as TODO

B #3559: Fix LXD market apps VM_Template

---

src/datastore_mad/remotes/lxd_downloader.sh

- Every app now follows the same procedure
https://github.com/OpenNebula/one/blob/b21d77484e164f7fecfc0e1550f667699cf3c8a4/src/datastore_mad/remotes/lxd_downloader.sh#L155-L159
- Critical operations during the auto-contextualization process are logged now into `/var/log/chroot.log` in the app file-system. 
- Applies to master and one-5.8
- Fixes #3663 
- Closes #3668
- [Docu PR](https://github.com/OpenNebula/docs/pull/743)

F #3668 B #3663 Generalize contextualization process

---

install.sh
share/hooks/vcenter/templates/create_vcenter_net.tmpl
share/hooks/vcenter/templates/delete_vcenter_net.tmpl
src/vmm_mad/remotes/lib/vcenter_driver/vcenter_importer.rb

vCenter hooks located at:
<ONE_LOCATION>/remotes/hooks/vcenter/templates
are registered automatically when import a vcenter cluster
with the command "onevcenter"

F #3380: Add auto-register vcenter hooks

---

src/onedb/onedb_live.rb

Fix bug when there are no consecutive VMs, so the get_page
function didn't return the pool.

M #-: fix bug in onedb purge done

---

share/hooks/vcenter/create_vcenter_net.rb
src/vmm_mad/remotes/lib/nsx_driver/opaque_network.rb
src/vmm_mad/remotes/lib/nsx_driver/virtual_wire.rb
src/vmm_mad/remotes/lib/vcenter_driver/datacenter.rb
src/vmm_mad/remotes/lib/vcenter_driver/network.rb

These attributes are added when importing a NSX network
NSX_ID
NSX_VNI
NSX_TZ_ID
Also now there is a different VCENTER_PORTGROUP_TYPE for
distributed port groups and NSX-V portgroups

F #3440: Improve NSX import process

---

src/sunstone/sunstone-server.rb

Build in functionality so Sunstone marks cookies set as Secure to ensure only secure servers can access the session cookie.
I've also made [a PR to OpenNebula/docs](https://github.com/OpenNebula/docs/pull/771) to document this change.
PS: It'd be nice to have a ISSUE_TEMPLATE so I know what GitCop expects so I don't make this mistake of writing PRs this way.

F #3738: Secure cookie flag if scheme is https

---

share/install_gems/install_gems

A warning added if `install_gems` are executed on a machine where packaged Ruby gems are installed and will be used no matter if install_gems is run or not. E.g.,
```
WARNING: Running install_gems is not necessary anymore, as all the
required dependencies are already installed by your packaging
system into symlinked location /usr/share/one/gems. Ruby gems
installed by this script won't be used until this symlink exists.
Remove the symlink before starting the OpenNebula services
to use Ruby gems installed by this script. E.g. execute
Execution continues in 15 seconds ...
```

F #2799: install_gems warns if gems are packaged

---

src/vmm_mad/remotes/lib/nsx_driver/opaque_network.rb
src/vmm_mad/remotes/lib/nsx_driver/virtual_wire.rb

This allows creation of opaque network and virtual wire
objects without id and tz id

F #3440: Allow logical switch empty constructor

---

src/sunstone/public/bower.json

Domain of the freedesktop.org has expired, so the build was failing due to unavailability of their GitLab server. Proposed change switches to their mirror located on GitHub.

M #-: Change Spice module from Freedesktop to GH

---

src/vmm_mad/remotes/kvm/detach_nic
src/vmm_mad/remotes/kvm/kvmrc
src/vmm_mad/remotes/kvm/restore

* return success if the MAC is not found
* retry few times before reporint detach failure
* option to define the number of retries (default is 3)

B #3873: fix race in vmm/kvm/detach_nic

---

src/tm_mad/qcow2/ln.ssh

Don't evaluate the presence of the SRC_SNAP_DIR on the hypervisor, but rather on the frontend to prevent the race condition.

B #3244: Prevent race condition in ln.ssh

---

share/oneprovision/ansible/roles/opennebula-repository/defaults/main.yml

Provision deployment will now fail until 5.10 is released.

M #-: Bump version in Ansible openenbula-repository

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

When a template or VM has a CDrom unit without file attached,
an error was raised trying to access to fileName attribute
because that attribute doesn't exist.

B #-: Fix fail access to fileName on empty CDs

---

src/im_mad/remotes/node-probes.d/numa.rb

following the description in CPUSET(7) man page:
List format
The List Format for cpus and mems is a comma-separated list of CPU or
memory-node numbers and ranges of numbers, in ASCII decimal.
Examples of the List Format:
0-4,9           # bits 0, 1, 2, 3, 4, and 9 set
0-2,7,12-14     # bits 0, 1, 2, 7, 12, 13, and 14 set

B #3972: normalize the list of cpus

---

src/oca/go/src/goca/schemas/acl/acl.go

Signed-off-by: Pierre Lafievre <pierre.lafievre@iguanesolutions.com>

B #3974: GOCA - fix 386 compilation fail on uint

---

share/doc/xsd/acl_pool.xsd

Although the format is hexadecimal, ONE produces
values where length is not even (without adding
leading zero). This violates xs:hexBinary type.

B #4076 Keep xs:integer type for acl

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

This allows attach IDE disk to VMS when the VM is
into powered off state.
The disk will have DEV_PREFIX="sd" by default, if you want
to have a DEV_PREVIX="hd" you need to change before into the
image template.

B #4087: Allows attach IDE disks

---

src/sunstone/public/app/tabs/vms-tab/panels/network.js

B #3882: fix IPv4 address not shown in VM network tab

---

share/doc/xsd/acl_pool.xsd

hexBinary fails due to non-even length
integer fails obviously when containig a-f chars

B #4076: Use xs:string for ACLs

---

src/oca/go/src/goca/datastore.go
src/oca/go/src/goca/document.go
src/oca/go/src/goca/image.go
src/oca/go/src/goca/marketplace.go
src/oca/go/src/goca/marketplace_test.go
src/oca/go/src/goca/marketplaceapp.go
src/oca/go/src/goca/schemas/shared/permissions.go
src/oca/go/src/goca/securitygroup.go
src/oca/go/src/goca/securitygroup_test.go
src/oca/go/src/goca/template.go
src/oca/go/src/goca/virtualnetwork.go
src/oca/go/src/goca/virtualrouter.go
src/oca/go/src/goca/virtualrouter_test.go
src/oca/go/src/goca/vm.go
src/oca/go/src/goca/vmgroup.go
src/oca/go/src/goca/vntemplate.go

Initial PR #4135 splitted in two, in order to move the breaking part only in this PR.
This part remove pointers used for permission structures.

[GOCA] permissions changes (breaking)

---

src/vmm_mad/remotes/kvm/detach_disk

B #4164: Use xmllint to test disk target device

---

src/vmm_mad/remotes/lib/lxd/container.rb

Removed small time window from stopping to flag the transition_start.
Applicable to master.

Flag container status transition before reboot.stop 

---

src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lxd/poll

Transition start flag was removed when stopping (@lxc gets overriden by change_state).
- removed reboot flags (using the transition methods now)
- added helper method
Applicable to master

B #3189: Update when flagging trans_start

---

src/vmm_mad/remotes/lxd/poll

`lxc_path` function always returned `nil` after merging [this](https://github.com/OpenNebula/one/pull/2840/files), triggering the rescue blocks and returning 0 for CPU and RAM monitoring functions.
Added some error logging in order to avoid silent fails like this one.
Merge with https://github.com/OpenNebula/docs/pull/969

Fix LXD CPU and Memory monitoring

---

src/onedb/onedb_backend.rb

B #4329: use default encoding if not found

---

src/onedb/fsck/quotas.rb

Use `PARENT_NETWORK_ID` instead of `AR/PARENT_NETWORK_AR_ID` to find parent network id
fixes https://github.com/OpenNebula/one/issues/4334

B #4334: fix reserved networks count

---

src/sunstone/public/build.sh

New **grunt** 1.1.0 introduces dependency on newer **mkdirp** module, which  is not compatible with Node.js in the build system.
```
opennebula-5.10.4/src/sunstone/public/node_modules/mkdirp/lib/opts-arg.js:7
opts = { mode: 0o777 & (~process.umask()), fs, ...opts }
^^^
SyntaxError: Unexpected token ...
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:549:28)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (/var/lib/jenkins/jobs/new-init/workspace/tmp.NBe8nTFP2g/opennebula-5.10.4/src/sunstone/public/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
```
Applies to
- master
- one-5.10
(and possibly other stable branches where cherry-pick fits)

M #-: Fix to grunt<1.1.0

---

src/sunstone/public/build.sh
src/sunstone/public/package.json

Previous change fixing Grunt to <1.1.0 was not enough, as the dependency on new one is introduced directly by Sunstone. So, it's more effective to pin the version in package file.
Applies to
- master
- one-5.10

M #-: Fix Sunstone dependency on grunt<1.1.0

---

src/cli/cli_helper.rb

New operator has been added for filtering in the CLI.
The new operator '~' will match sub keys, not exact, e.g:
If NAME is 'testing' with --filter NAME=tes wont't match but NAME~tes yes

F #2506: improve CLI filtering matching

---

share/start-scripts/cron_start_script

net.ipv4.ip_forward is always set to 1 in every recontextualization if
cron_start_script used as start script.

M #-: Grant ipforwarding in every recontext

---

src/im_mad/remotes/lib/nsx.rb
src/im_mad/remotes/lib/vcenter.rb
src/vnm_mad/remotes/vcenter/clean
src/vnm_mad/remotes/vcenter/post
src/vnm_mad/remotes/vcenter/pre

- VMs with name one-xxx was not been monitored
- Change NSX_STATUS='' on hosts with no NSX
- Changes on checkings in VNM driver
- Change an error ocurring connecting to NSX Manager

F #4302: Fixes included

---

share/pkgs/ssh/config
share/pkgs/ssh/config-7.6+
share/pkgs/ssh/config-pre7.6
src/mad/ruby/ssh_stream.rb
src/mad/sh/scripts_common.sh

- add two configs for OpenSSH <7.6 and >=7.6
- enable SSH session sharing via master socket
- disable SSH session sharing when ssh-agent is forwarded

F #1473: Add oneadmin's SSH config

---

share/pkgs/services/systemd/opennebula.service
share/ssh/bin/ssh
share/ssh/etc/config
share/ssh/etc/config-pre7.6

- add ssh wrapper which is used only on the fronted
- disable SSH master socket on the nodes
- add new PATH and SSH_USE_MASTER_SOCK into opennebula.service

F #1473: Fix SSH persistent connections

---

install.sh
src/market_mad/remotes/common/lxd.rb
src/market_mad/remotes/linuxcontainers/monitor
src/market_mad/remotes/turnkeylinux/monitor

- Added a lib for LXD markets. ATM, generates the template, but there is a lot of repeated code in turnkey and linuxcontainers.org market that can be pushed onto the lib and called as functions.
- Added SCHED_REQUIREMENTS to the template Apps
Closes #4669 
Merge with https://github.com/OpenNebula/docs/pull/1116

F #4669: QoL scheduling for LXD apps

---

src/market_mad/remotes/turnkeylinux/monitor

Fixes Turnkey monitoring fail
```
9JRD48VUlEPjA8L1VJRD48R0lEPjA8L0dJRD48VU5BTUU+b25lYWRtaW48L1VOQU1FPjxHTkFNRT5vbmVhZG1pbjwvR05BTUU+PE5BTUU+VHVybktleSBMaW51eCBDb250YWluZXJzPC9OQU1FPjxNQVJLRVRfTUFEPjwhW0NEQVRBW3R1cm5rZXlsaW51eF1dPjwvTUFSS0VUX01BRD48Wk9ORV9JRD48IVtDREFUQVswXV0+PC9aT05FX0lEPjxUT1RBTF9NQj4wPC9UT1RBTF9NQj48RlJFRV9NQj4wPC9GUkVFX01CPjxVU0VEX01CPjA8L1VTRURfTUI+PE1BUktFVFBMQUNFQVBQUz48L01BUktFVFBMQUNFQVBQUz48UEVSTUlTU0lPTlM+PE9XTkVSX1U+MTwvT1dORVJfVT48T1dORVJfTT4xPC9PV05FUl9NPjxPV05FUl9BPjE8L09XTkVSX0E+PEdST1VQX1U+MTwvR1JPVVBfVT48R1JPVVBfTT4wPC9HUk9VUF9NPjxHUk9VUF9BPjA8L0dST1VQX0E+PE9USEVSX1U+MTwvT1RIRVJfVT48T1RIRVJfTT4wPC9PVEhFUl9NPjxPVEhFUl9BPjA8L09USEVSX0E+PC9QRVJNSVNTSU9OUz48VEVNUExBVEU+PERFU0NSSVBUSU9OPjwhW0NEQVRBW1R1cm5LZXkgbGludXggaXMgYSBmcmVlIHNvZnR3YXJlIHJlcG9zaXRvcnkgYmFz …
```

F #4089: Fix Turnkey link

---

share/linters/.rubocop.yml
src/vnm_mad/remotes/lib/vlan.rb

As this action is potentialy racy
rc=2 is for `RTNETLINK answers: File exists`

B #4794: Allow rc=2 when creating bridge

---

src/mad/ruby/scripts_common.rb

Requires at begining of file my cause errors on hypervisors, move them to send_to_monitor function as this function should be used only on front_end.
Added basic error handling

B #4793: Move requires to function, rescue errors

---

include/SqliteDB.h
share/etc/oned.conf
src/monitor/src/monitor/Monitor.cc
src/nebula/Nebula.cc
src/sql/SqliteDB.cc

Not sure if it's still time to make changes to oned.conf for 5.12. If not, I can remove the configuration and use only the sqlite3_busy_timeout() for setting timeout.
Default value 2500 is same as in old SQLITE_BUSY handling, but works much better. I don't have any SQLITE_BUSY error even with 100 ms timeout

M #-: Configurable timeout for SQLite DB

---

src/im_mad/im_exec/one_im_sh

Some platforms has "ruby" just a wrapper to particular interpreter:
```
\_ /usr/lib/one/mads/onemonitord -c monitord.conf
\_ /usr/bin/ruby-mri /usr/lib/one/mads/one_im_exec.rb -r 3 -t 15 -w 90 firecracker
\_ /usr/bin/ruby-mri /usr/lib/one/mads/one_im_exec.rb -r 3 -t 15 -w 90 kvm
\_ /usr/bin/ruby-mri /usr/lib/one/mads/one_im_exec.rb -r 3 -t 15 -w 90 lxd
\_ /usr/bin/ruby-mri /usr/lib/one/mads/one_im_exec.rb -l -c -t 15 -r 0 vcenter
\_ /usr/bin/ruby-mri /var/lib/one/remotes/im/lib/vcenter_monitor.rb
```

M #-: vCenter IM process check fix

---

install.sh

According to FHS the directory should be /usr/share/doc/ instead of
/usr/share/docs/ (https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html)

M #-: Move docs to /usr/share/doc/

---

src/oca/go/src/goca/vm.go

Fix two issues:
- methods that create resources should returns -1 as an error ID
- one.vm.disksnapshotcreate should return the ID of the new snapshot

B-4921: GOCA -small fixes on VM disk snapshot methods

---

src/oca/go/src/goca/schemas/acl/acl.go

This PR implements the ACL Utilities found in the pytthon, java and ruby client in goca. I've implemented this code before for the [terraform-provider-opennebula](https://github.com/terraform-providers/terraform-provider-opennebula), so this PR just backports it.

oca/goca: add ACL Utilities

---

src/vm/VirtualMachinePool.cc

Bug fix for issue: https://github.com/OpenNebula/one/issues/5081
Signed-off-by: Romanov Andrey Grigorievich <romanov.andrey.grigorievich@gmail.com>

B#5081: oned monitoring API bug with PostgreSQL

---

share/onegate/onegate

To solve the bug #5258: Onegate ruby client do not terminate a VM (nor other similar operations)

B #5258: Onegate ruby client do not terminate a VM (nor other similar operations)

---

src/oca/go/src/goca/dynamic/dyntemplate.go

This fix should also be backported for some previous versions. 
At least for the 5.12 version, which is used by terraform provider

B #5477: GOCA - fix Del template method

---

src/authm_mad/remotes/ldap/ldap_auth.rb

When a match is made, the username is changed. It's then inappropriate to attempt further matches because we're not using the original username.
If multiple matches were made with the original username, there could be no single modified username to return. An alternative would be to return pairs of server and modified username.
Fixes #5513.

Stop at the first match for LDAP match_user_regex option

---

src/oca/go/src/goca/schemas/host/host.go

Update host schema:
- remove attributes from share 
- add monitoring as a dynamic part
- add NUMA section
It would be nice to have it merged for all versions from 5.12.

F-5656: GOCA - update host schema

---

src/oca/go/src/goca/virtualnetwork.go

In case of an error, the method panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
```

B #5663: GOCA - fix vnet reserve method

---

src/oca/go/src/goca/dynamic/dyntemplate.go

In dynamic GOCA templates values are escaped via the `Quote` method. This also escape newline characters.
This PR try to keep using Quote to escape template pair values except for multiline values.
For the multiline case escaping will probably less accurate and strict than with quote.
Tested with some minimal sample of code:
```
func main() {
tpl := vm.NewTemplate()
tpl.Add("CPU", "1")
tpl.Add("SCHED_REQUIREMENTS", `CLUSTER_ID!="123"`)
tpl.Add("MEMORY", "1")
tpl.Add("KEY", `line1 "
line2`)
tpl.Add("KEY2", "")
tpl.Add("KEY3", `	ⓗ"']\[`)
tpl.Add("NAME", "toto")
fmt.Println(tpl.String())
}
```
Close #5914

B #5914: GOCA - fix newline escaping in template values

---

src/sunstone/public/app/opennebula/vm.js

From OpenNebula version 6, there are changes in Sunstone regarding how IP addresses are shown. Few bugs:
- Only one IP address is show per NIC
- It show IP6_GLOBAL only if IP6_ULA is also defined
I fixed both bugs in this PR, check screenshots.

M #-: Sunstone - fixed showing IP6_GLOBAL addresses

---

src/im_mad/remotes/lib/vcenter_cluster.rb

Fix filtering on host id when monitoring vcenter vms to correctly determine corresponding opennebula vm id

---

src/oca/go/src/goca/context_test.go
src/oca/go/src/goca/helper_test.go
src/oca/go/src/goca/hook_test.go
src/oca/go/src/goca/virtualnetwork_test.go
src/oca/go/src/goca/virtualrouter_test.go
src/oca/go/src/goca/vm_test.go

Modifies the GOCA tests to address cases of intermittent test failures, particularly when working with resources that are not ready yet. This update aims to enhance test reliability by adding controls to ensure that the desired state is achieved before managing resources.
Modified tests:
- vm
- context
- hook
- virtualrouter 
- virtualnetwork
Depends on [#2645](https://github.com/OpenNebula/development/pull/2645)
<hr>

F #783 Fix randomly failing GOCA tests

---

src/im_mad/remotes/node-probes.d/numa_host.rb

This small change avoids errors in the numa_host.rb probe when executed on systems without NUMA support, such as Raspberry Pi or other ARM64 SBCs.
The probe now exits cleanly if NUMA::NODE_PATH does not exist.
<hr>

F: Skip NUMA probe on systems without NUMA (e.g. ARM64 boards)
