OpenNebula/one

src/datastore_mad/remotes/ceph/monitor

There are some inconsistent variables and some unescaped special characters that prevent this script from working for me.

3 small updates to fix the monitor script

---

src/mad/sh/scripts_common.sh

Check against exec rc from the ssh session.

fix ssh_make_path function

---

src/vmm_mad/remotes/kvm/migrate_local

Added MIGRATE_OPTIONS variable to sync with the remote `migrate` script

fix vmm/kvm/migrate_local

---

share/man/onetemplate.1
share/man/onevm.1
src/cli/one_helper.rb

http://dev.opennebula.org/issues/4399

Feature #4399: Add VNC/Spice keymap option to the CLI

---

src/sunstone/public/app/opennebula/auth.js

This is a small fix to solve sunstone remote_user login issue.
http://dev.opennebula.org/issues/4748

Bug #4748: Fix sunstone remote_auth login

---

src/vmm_mad/remotes/vcenter/vcenter_driver.rb

Under SDRS, Datastore entities are placed inside StoragePod entities.

F #4584: Add support for SDRS clustered vCenter datastores

---

src/sunstone/public/app/opennebula/vm.js
src/vmm_mad/remotes/vcenter/vcenter_driver.rb

Network monitoring info (real-time data) is gathered from Performance Manager. Also some trailing spaces are removed by VSCode from vcenter_driver.rb.

F #4647. Add network monitoring to vCenter drivers

---

src/sunstone/etc/sunstone-views/admin.yaml
src/sunstone/etc/sunstone-views/cloud.yaml
src/sunstone/etc/sunstone-views/groupadmin.yaml
src/sunstone/public/app/sunstone-config.js

- new tag 'confirm_vms' in .yalm files
- change in users: cloud, admin and groupadmin

F #4826: Confirm all vms actions

---

src/sunstone/public/app/tabs/vms-tab/panels/info.js
src/sunstone/public/app/tabs/vms-tab/panels/info/html.hbs
src/sunstone/public/app/tabs/vms-tab/utils/datatable-common.js

B #4800 Sunstone show IP on main info page

---

src/sunstone/views/index.erb
src/sunstone/views/login.erb

- new tag meta in index.erb and login.erb for force the compatibility mode off

F #4841 IE Compatibility mode force off

---

src/sunstone/public/app/tabs/vms-tab/buttons.js
src/sunstone/public/app/tabs/vms-tab/dialogs/vnc/html.hbs

Choose only the commit new tag and change color VNC

Feature 4838 and Feature 4826 (buttons.js new variable)

---

src/sunstone/public/css/custom.css
src/sunstone/public/scss/_menu.scss
src/sunstone/public/scss/_settings.scss
src/sunstone/public/scss/app.scss
src/sunstone/views/index.erb

- changed some SCSS file to work with labels
- Added link custom.css in index.erb

F #4373 Added a custom css file in css folder

---

src/vmm_mad/remotes/vcenter/vcenter_driver.rb

This fix also contains code for fix the duplicated NICs issue that was added to master.

B#4897 Fix situations that would cause NICs not being removed (one 5.2)

---

src/vmm_mad/remotes/vcenter/vcenter_driver.rb

Add code to fix cases that were not discovered previously where NICs were not removed from vCenter if they were removed from OpenNebula when the VM was in POWEROFF.

B#4897 Fix NICs not being removed from vCenter (master)

---

src/vnm_mad/remotes/OpenNebulaNetwork.conf
src/vnm_mad/remotes/vxlan/vxlan_driver.rb

Add default MTU for the VXLAN interface.

Add default MTU for the VXLAN interface

---

src/sunstone/public/app/utils/range-slider.js

Max input slider

---

src/sunstone/public/app/tabs/oneflow-templates-tab/utils/role-tab.js

B Flow resolved bug of roles

---

include/NebulaTemplate.h
share/etc/oned.conf
src/datastore/Datastore.cc
src/datastore_mad/remotes/fs/cp
src/nebula/NebulaTemplate.cc
src/onedb/local/4.90.0_to_5.3.80.rb

https://dev.opennebula.org/issues/3705

B #3705 Allow DRIVER override on datastore level

---

src/sunstone/public/scss/app.scss

Added new attribute for view colors in meter input

F #ColorMeter

---

src/vmm_mad/remotes/ec2/ec2_driver.rb

i've been improved wait_state function 4 robust code.

few changes around ec2 driver state switching

---

src/vmm_mad/remotes/ec2/ec2_driver.rb

ec2 instance monitoring now is working properly.
known issues: too much time to sincronize beetween  aws monitoring host <---> oneHost

B #5011 fixed: ec2 instances monitoring

---

src/sunstone/public/app/tabs/vnets-tab/form-panels/create.js
src/sunstone/public/app/tabs/vnets-tab/utils/ar-tab/html.hbs

Hide security groups section when vcenter is selected

Feature vcenter-secGroups 

---

src/raft/RaftManager.cc
src/rm/Request.cc

…of the zone would be given "the" would not be needed.

Some more small typo / grammer fixes

---

share/instance_types/az-instance-types.rb
share/instance_types/ec2-instance-types.rb
src/vmm_mad/remotes/az/az_driver.conf
src/vmm_mad/remotes/ec2/ec2_driver.conf

-instance_types scripts 4 both providers are fixed.
-now you can generate directly the conf file
-changed conf files due to proper scripts mod

B #5340 ec2, azure instance types 

---

install.sh
src/onedb/local/5.4.0_to_5.5.80.rb

Migrator started and ready 4 azure new auth system.

F #5189 azure migrator

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/actions.js
src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js
src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate/templateRow.hbs
src/sunstone/public/app/utils/actions.js

Modularized actions in utils/actions.js

F #5118 Allow SCHEDULED ACTIONS in VM Templates

---

src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js
src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate/templateRow.hbs
src/sunstone/public/app/utils/disks-resize.js

Improved VM intantiation view and solved bug in range-slider

F #5366: Improved VM intantiation view

---

src/sunstone/public/app/tabs/users-tab/panels/groups.js

- selected in primary group input the effective group.
- changed order in the group actions: first change the primary group and, then, the secondaries.

B #5378: Edit user's groups in Sunstone

---

src/vmm_mad/remotes/lib/vcenter_driver/vi_helper.rb

should be cherrypicked into master

B #5286: find_by_ref hotFix

---

src/dm/DispatchManagerActions.cc

should be cherrypicked into master

B #5356: (vcenter) core crash on hold hotfix

---

src/sunstone/routes/vcenter.rb
src/vmm_mad/remotes/lib/vcenter_driver/importer.rb
src/vmm_mad/remotes/lib/vcenter_driver/vi_helper.rb

B #5458: onevcenter does not allow to import without a valid cluster, sunstone cache invalidation

---

src/ipamm_mad/remotes/dummy/get_address
src/ipamm_mad/remotes/dummy/register_address_range

Changed ipam driver to pass the tests

---

src/sunstone/public/app/tabs/provision-tab.js
src/sunstone/public/app/tabs/vms-tab/dialogs/disk-resize.js
src/sunstone/public/app/utils/disks-resize.js
src/sunstone/public/app/utils/range-slider.js
src/sunstone/public/app/utils/range-slider/html.hbs
src/sunstone/public/app/utils/user-inputs.js

B #5556: Disk size slider only goes up to 508GB

---

src/im_mad/collectd/SConstruct

No documentation change necessary (IMHO), it fixes a problem introduced by a recent commit.
Merge into one-5.4 and cherry pick commit into master.

Add missing crypto libs dependencies to collectd

---

src/vmm_mad/remotes/lib/vcenter_driver/importer.rb
src/vmm_mad/remotes/lib/vcenter_driver/network.rb
src/vmm_mad/remotes/lib/vcenter_driver/vi_helper.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #1538: create_one_network created, it handles cluster selection

F #1538: import virtual_machines and templates networking update

---

src/sunstone/public/app/sunstone.js
src/sunstone/public/app/utils/labels/utils.js

regex expresion for id now accepts strings, utils.js/getLabel checks if template exists.

 Changes for new addons.

---

src/oca/ruby/opennebula/pool_element.rb
src/oca/ruby/opennebula/virtual_machine.rb
src/oca/ruby/opennebula/xml_element.rb

F #1750: added method xmlelement to set content
F #1750: replace method works for all one objects

F #1750: Added method to oca for replacing TEMPLATE attributes

---

src/vrouter/VirtualRouter.cc

B #1680: Fixed bug when deleting a virtual router with floating IP

---

src/sunstone/views/_login_standard.erb
src/sunstone/views/_login_x509.erb

Fixes Lastpass 'LastPass detected a login form that is insecure' message
https://dev.opennebula.org/issues/5108

Explicitly define form method

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #1754: Fix get keymap from vcenter_driver.default file

---

src/vnm/AddressRange.cc

B #1832: seed is no longer generated when creating AR

---

src/sunstone/public/app/tabs/provision-tab.js
src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js
src/sunstone/public/app/utils/disks-resize.js

B #1844: VM instantiate disk size missing MB/GB selector

---

src/sunstone/public/app/tabs/vms-tab/dialogs/spice/html.hbs
src/sunstone/public/app/tabs/vms-tab/dialogs/vnc/html.hbs

B #1851: Button for vnc and spice is not displayed

---

src/sunstone/public/scss/app.scss

B #1846: Recycle icon broken in VM instantiation

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

B #1841 Improve error message when Import Wild or VM Template with disks without back reference

---

src/sunstone/public/app/tabs/vms-tab/panels/log.js

B #1778: VM log doesn't escape markup characters

---

src/vrouter/VirtualRouter.cc

B #1680: Prepared nic when instantiate a Virtual Router with FLOATING_IP

---

src/scheduler/etc/sched.conf

F #1843: Added new atribute to sched.conf

---

share/etc/oned.conf

F #1885: Added information to oned.conf

---

include/LoginToken.h
src/um/LoginToken.cc
src/um/UserPool.cc

B #1869: Checked if token has expired

---

src/rm/RequestManagerRename.cc

B #1893: Fixed bug when update hostname

---

src/cli/cli_helper.rb

Added != operator to filter.

---

src/sunstone/public/app/addons/README
src/sunstone/public/app/addons/tabs/README
src/sunstone/public/app/main.js

removed old addons structure references

Removed README files for avoiding folder generation with scons

---

include/Vdc.h
src/vdc/Vdc.cc

F #1872: Added option to not ask to the user

---

src/lcm/LifeCycleActions.cc
src/lcm/LifeCycleStates.cc

B #1797: Checked for the same host

---

src/sunstone/public/app/tabs/support-tab/buttons.js

Changed sign-out button into support tab [FA upgrade]

---

src/sunstone/public/app/tabs/images-tab/form-panels/create-common.js
src/sunstone/public/app/tabs/images-tab/form-panels/create/wizard.hbs

B #1960: Introduced the possibility to select empty value for persitent attribute

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #1518 Configured IP on imported VMs

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

bug applies to f1518 (merged in 1990)

#1990 fixed bug when importing a template.

---

src/vmm_mad/remotes/lib/vcenter_driver/importer.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #1518: Configure Ips when import wild from vCenter

---

src/rm/RequestManagerVirtualMachine.cc

B #2029: fixed bug with updateconf and vnc port

---

src/cli/one_helper.rb
src/cli/onevm

F #1509: Added more data to the description and possibility to introduce TiB

---

include/AddressRange.h
include/AddressRangePool.h
include/VirtualNetwork.h
include/VirtualNetworkPool.h
src/vm/VirtualMachineNic.cc
src/vnm/AddressRangePool.cc
src/vnm/VirtualNetwork.cc
src/vnm/VirtualNetworkPool.cc

F #1976: Using also the security groups of the VNet and their ARs

---

src/sunstone/etc/sunstone-views/kvm/cloud.yaml
src/sunstone/etc/sunstone-views/mixed/cloud.yaml
src/sunstone/etc/sunstone-views/vcenter/cloud.yaml
src/sunstone/public/app/tabs/provision-tab/vms/list.js

F #1479: Give the possibility to hide vCenter info in cloud view

---

src/datastore/Datastore.cc
src/rm/RequestManagerAllocate.cc

B #1512: Defining precedence of attributes

---

src/sunstone/sunstone-server.rb

Revert "F #1692: SUNSTONE_LOCATION fixed"

---

src/cli/one_helper/onevcenter_helper.rb
src/cli/onevcenter
src/vmm_mad/remotes/lib/vcenter_driver/network.rb
src/vmm_mad/remotes/lib/vcenter_driver/vcenter_importer.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

=========================================================
F #1884: it is possible to import objects with a single ID
F #1884: its possible to add defaults file [vcenter Importer]
F #1884: STDOUT changes around networks and template questions

F #1884: Bug fixes, STDOUT changes, IMPORT ID funcionality

---

src/cli/oneuser

B #2064 fixed oneuser passwd command error message improvement 

---

src/vmm/LibVirtDriverKVM.cc

F #1688: Changed cpu mode and fallback

---

include/ScheduledAction.h
include/VirtualMachine.h
src/scheduler/src/sched/Scheduler.cc
src/vm/VirtualMachine.cc
src/vm_template/ScheduledAction.cc
src/vm_template/VMTemplate.cc

F #1548: Fixed bug and added post_update_template

---

src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js
src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate/templateRow.hbs
src/sunstone/public/app/tabs/vms-tab/panels/actions.js
src/sunstone/public/app/utils/nics-section.js
src/sunstone/public/app/utils/nics-section/html.hbs
src/sunstone/public/app/utils/schedule_action.js
src/sunstone/public/app/utils/schedule_action/table.hbs

Changes in Sunstone with schedule actions and instantiate dialog

---

include/ScheduledAction.h
src/vm_template/ScheduledAction.cc

F #1548: Fixed bug with don't have END_TYPE

---

src/vm/VirtualMachineDisk.cc

Fixed bug when try to instantiate as persistent

---

src/vm_template/ScheduledAction.cc

Changed error message for month

---

src/sql/LogDB.cc

Changed SQL query to delete only non federated logs

---

src/sunstone/public/app/tabs/vnets-tab/utils/ar-tab.js
src/sunstone/public/app/tabs/vnets-tab/utils/ar-tab/html.hbs

B #2188: Fixed bug when tried to update address range with IP6_STATIC

---

share/pkgs/CentOS/opennebula.sudoers
share/pkgs/Debian7/opennebula.sudoers
share/pkgs/Debian8/opennebula.sudoers
share/pkgs/Ubuntu/opennebula.sudoers
share/pkgs/openSUSE/opennebula.sudoers
share/sudoers/sudo_commands.rb
src/mad/sh/scripts_common.sh
src/tm_mad/fs_lvm/resize

I have implemented the method "resize" for the fs_lvm storage driver. Could you accept one.

Driver fs_lvm. method resize has been implemented

---

include/RaftManager.h
include/RequestManagerZone.h
src/cli/onezone
src/oca/ruby/opennebula/zone.rb
src/raft/RaftManager.cc
src/rm/RequestManager.cc
src/rm/RequestManagerZone.cc

Feature 2143 call

---

src/vmm_mad/remotes/ec2/cancel
src/vmm_mad/remotes/ec2/ec2_driver.conf
src/vmm_mad/remotes/ec2/ec2_driver.rb

Don't squash both commits, they have been already squashed.

Feature 2291

---

src/mad/ruby/scripts_common.rb
src/tm_mad/vcenter/mv
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/vcenter/migrate
src/vmm_mad/remotes/vcenter/save

======================================
B #2230: ruby fuctions from sh commons
B #2230: migrate routine added, now vCenter vms migrate with relocate_spec
B #2230: cold migrate now works as expected, small ruby common fix
B #2230: vCenter cold/hot migrate fix

B #2230: vCenter driver migrate feedback, esx bug fixed

---

src/vmm_mad/remotes/ec2/ec2_driver.rb

Changed is_pm by provision_type.
Applies to master + 5.6.

Fixed PM_MAD.

---

install.sh
src/vmm_mad/remotes/lib/vcenter_driver/vcenter_driver.conf
src/vmm_mad/remotes/lib/vcenter_driver/vi_client.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/vcenter/deploy
src/vmm_mad/remotes/vcenter/vcenter_driver.rb

B #2262 (vCenter) wait poweron/off to be performed

---

src/vmm_mad/remotes/lib/vcenter_driver/vi_client.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

B #2262 make the code more robust

---

src/sunstone/public/app/utils/quotas/quota-widgets.js

B #2316: User quotas error

---

src/sunstone/public/app/utils/accounting.js

B #2315: Accounting data doesn't display

---

src/cli/command_parser.rb

Cherry-pick to one-5.6 branch
Link to documentation PR: https://github.com/OpenNebula/docs/pull/337

B #2254 spurios syntax help on onehost delete

---

src/sunstone/etc/sunstone-views/kvm/admin.yaml
src/sunstone/etc/sunstone-views/kvm/cloud.yaml
src/sunstone/etc/sunstone-views/kvm/groupadmin.yaml
src/sunstone/etc/sunstone-views/kvm/user.yaml
src/sunstone/etc/sunstone-views/mixed/admin.yaml
src/sunstone/etc/sunstone-views/mixed/cloud.yaml
src/sunstone/etc/sunstone-views/mixed/groupadmin.yaml
src/sunstone/etc/sunstone-views/mixed/user.yaml
src/sunstone/etc/sunstone-views/vcenter/admin.yaml
src/sunstone/etc/sunstone-views/vcenter/cloud.yaml
src/sunstone/etc/sunstone-views/vcenter/groupadmin.yaml
src/sunstone/etc/sunstone-views/vcenter/user.yaml

B #2331: No way for hide Lock/Unlock button for VM in Sunstone view

---

src/sunstone/public/app/tabs/settings-tab/panels/user-config/html.hbs

Change view icon broken in cloud view settings

---

src/sunstone/public/app/tabs/provision-tab/flows/list.js

Cardinality button icon broken in cloud view

---

src/cli/one_helper/onezone_helper.rb
src/cli/onezone

F #2190 Onezone set should allow temporary zone changes

---

src/vmm_mad/remotes/lib/vcenter_driver/vcenter_driver.conf
src/vmm_mad/remotes/vcenter/attach_disk
src/vmm_mad/remotes/vcenter/attach_nic
src/vmm_mad/remotes/vcenter/cancel
src/vmm_mad/remotes/vcenter/deploy
src/vmm_mad/remotes/vcenter/detach_disk
src/vmm_mad/remotes/vcenter/detach_nic
src/vmm_mad/remotes/vcenter/migrate
src/vmm_mad/remotes/vcenter/poll
src/vmm_mad/remotes/vcenter/reboot
src/vmm_mad/remotes/vcenter/reconfigure
src/vmm_mad/remotes/vcenter/reset
src/vmm_mad/remotes/vcenter/restore
src/vmm_mad/remotes/vcenter/save
src/vmm_mad/remotes/vcenter/shutdown
src/vmm_mad/remotes/vcenter/snapshot_create
src/vmm_mad/remotes/vcenter/snapshot_delete
src/vmm_mad/remotes/vcenter/snapshot_revert

F #2341 Add debug information to vCenter drivers (stacktrace)

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #2293 NIC Model is ignored on VM vCenter Template

---

src/sunstone/models/OpenNebulaJSON/VirtualNetworkJSON.rb

B #2348: Error when creating a vnet from Sunstone using advanced mode

---

src/datastore_mad/remotes/downloader.sh
src/datastore_mad/remotes/vcenter/cp

Migrate images to/from KVM / vCenter DS

---

src/um/Quota.cc

F #2228: Fixed problem with defualt quotas

---

src/datastore_mad/remotes/downloader.sh

Fix one bug and add if statement just in case the image and the origin have diferent image type.

F #2320 Migrate images to/from KVM / vCenter DS

---

src/sunstone/public/app/tabs/groups-tab/form-panels/create/wizard.hbs
src/sunstone/public/app/tabs/secgroups-tab/panels/vms.js
src/sunstone/public/app/tabs/secgroups-tab/panels/vms/html.hbs
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/network/nic-tab.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/network/nic-tab/html.hbs
src/sunstone/public/app/tabs/vnets-tab/form-panels/create/wizard.hbs
src/sunstone/public/app/utils/tab-datatable.js

B #2394: Improve the dialog when attach nic in vnet tab

---

src/rm/RequestManagerChown.cc

F #2228: Fixed bug with Chown action and running quotas

---

src/template/Template.cc

B #2402: Fixed bug with restricted attributes when extra template is empty

---

src/sunstone/public/css/custom.css

Add spacing to VM tags

---

src/template/Template.cc

B #2402: Changed restricted_attribute fuction to return a boolean

---

src/rm/RequestManagerChown.cc

F #2260: Fixed problem with generic function chown

---

include/RequestManagerChown.h
src/rm/RequestManagerChown.cc

F #2260: Added new wrapper to pass Pool and ObjectType

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/storage/disk-tab/options.hbs

B #2423: OPENNEBULA_MANAGED deleted when updating a VM Template

---

src/vmm_mad/remotes/lxd/deploy
src/vmm_mad/remotes/lxd/lib/lxd_driver.rb

- Parsing XML elements using the existing methods ("retrieve_xmlelements" and "[]") inside OpenNebula module.
- Module LXDdriver created
- Class Info created and methods to build the container config hash created (memory, cpu, name)

XML parser and container info builder

---

include/History.h
include/RequestManagerVirtualMachine.h
include/Snapshots.h
include/VirtualMachine.h
include/VirtualMachineDisk.h
share/doc/xsd/acct.xsd
share/doc/xsd/vm.xsd
src/cli/onevm
src/nebula/NebulaTemplate.cc
src/oca/go/src/goca/vm.go
src/oca/java/src/org/opennebula/client/vm/VirtualMachine.java
src/oca/ruby/opennebula/virtual_machine.rb
src/rm/RequestManager.cc
src/rm/RequestManagerVirtualMachine.cc
src/vm/History.cc
src/vm/Snapshots.cc
src/vm/VirtualMachineDisk.cc

F #1147: Permit to rename disk snapshot names

---

src/vmm_mad/remotes/lib/vcenter_driver/datastore.rb

B #2437: importing resources from vCenter ds with weird names

---

src/sunstone/public/app/tabs/images-tab/panels/snapshots.js
src/sunstone/public/app/tabs/vms-tab/panels/storage.js

B #2439: Active disk snapshot is missing arrow in Sunstone

---

src/sunstone/public/app/utils/labels/tree.js
src/sunstone/public/app/utils/labels/utils.js

B# 2473: Labels format

---

src/sunstone/OpenNebulaVNC.rb
src/vmm_mad/remotes/lib/vcenter_driver/importer.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/vcenter/deploy

B #2477 VCENTER_ESX_HOST fail with DRS in vCenter

---

src/sunstone/etc/sunstone-views/kvm/admin.yaml
src/sunstone/etc/sunstone-views/kvm/cloud.yaml
src/sunstone/etc/sunstone-views/kvm/groupadmin.yaml
src/sunstone/etc/sunstone-views/kvm/user.yaml
src/sunstone/etc/sunstone-views/mixed/admin.yaml
src/sunstone/etc/sunstone-views/mixed/cloud.yaml
src/sunstone/etc/sunstone-views/mixed/groupadmin.yaml
src/sunstone/etc/sunstone-views/mixed/user.yaml
src/sunstone/etc/sunstone-views/vcenter/admin.yaml
src/sunstone/etc/sunstone-views/vcenter/cloud.yaml
src/sunstone/etc/sunstone-views/vcenter/groupadmin.yaml
src/sunstone/etc/sunstone-views/vcenter/user.yaml
src/sunstone/models/OpenNebulaJSON/VirtualMachineJSON.rb
src/sunstone/public/app/opennebula/vm.js
src/sunstone/public/app/tabs/provision-tab.js
src/sunstone/public/app/tabs/vms-tab.js
src/sunstone/public/app/tabs/vms-tab/actions.js
src/sunstone/public/app/tabs/vms-tab/dialogs/disk-snapshot-rename.js
src/sunstone/public/app/tabs/vms-tab/dialogs/disk-snapshot-rename/dialogId.js
src/sunstone/public/app/tabs/vms-tab/dialogs/disk-snapshot-rename/html.hbs
src/sunstone/public/app/tabs/vms-tab/panels/storage.js
src/sunstone/public/app/tabs/vms-tab/panels/storage/disk-details.hbs

F #1147: Permit to rename disk snapshot names in Sunstone

---

src/sunstone/public/app/tabs/vms-tab/buttons.js

F #1246 Re-import Wild VMs

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

B #2474 Network model is not working in vCenter

---

include/AddressRange.h
include/IPAMManager.h
include/IPAMManagerDriver.h
install.sh
src/ipamm/IPAMManager.cc
src/ipamm_mad/one_ipam.rb
src/ipamm_mad/remotes/dummy/unregister_address_range
src/vnm/AddressRangePool.cc

* Modify the IPAM driver
* Modify AddressRangePool to call the new action script
* Add example dummy script

F #2490: Add new unregister address range functionality

---

src/sunstone/public/app/tabs/vmgroup-tab/form-panels/create.js

B #2522: Impossible to create vmgroup using advanced mode

---

src/sunstone/public/app/utils/disks-resize.js

B #2533: Impossible to instantiate a VM w/ RESTRICTED_ATTR DISK/SIZE

---

src/sunstone/public/app/tabs/images-tab/form-panels/create-common.js
src/sunstone/public/app/tabs/images-tab/form-panels/create/wizard.hbs

F #1089 Allow creation of Empty disk image for type OS

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/network/nic-tab.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/network/nic-tab/html.hbs
src/sunstone/public/app/utils/nics-section.js
src/sunstone/public/app/utils/nics-section/dd.hbs

F #2427: Added possibility to select SCHED_REQUIREMENTS from vnet datatable

---

src/vm/VirtualMachine.cc

B #2540: Fixed bug after delete FILES_DS

---

share/doc/xsd/group.xsd
share/doc/xsd/group_pool.xsd
share/doc/xsd/host.xsd
share/doc/xsd/image.xsd
share/doc/xsd/user.xsd
share/doc/xsd/user_pool.xsd
share/doc/xsd/vm.xsd
share/doc/xsd/vnet.xsd
share/doc/xsd/vnet_pool.xsd

F #2426: Updated xsd

---

src/cli/onevdc

Changed casecmp? function by upcase and comparation

---

src/cli/onevnet

Fixed bug with %r expression

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

B #2558: reference unmanaged nics is working

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/vcenter/deploy

all branches:
- master
- 5.6
- 5.6-devel

B #2552: improve resume/poweroff vcenter actions

---

include/Datastore.h
include/VirtualMachine.h
include/VirtualMachineDisk.h
src/datastore/Datastore.cc
src/rm/RequestManagerVirtualMachine.cc
src/vm/VirtualMachine.cc
src/vm/VirtualMachineDisk.cc

B #2544: Set LN_TARGET and CLONE_TARGET after pick the datastore

---

src/vm/VirtualMachineDisk.cc

B #2544: Fixed bug with CONTEXT and volatile disks

---

install.sh
src/vmm_mad/remotes/lib/vcenter_driver/datastore.rb
src/vmm_mad/remotes/vcenter/vcenter_driver.rb
src/vmm_mad/remotes/vcenter/vcenterc

F #2454: added vcenterc config file

---

src/mad/sh/scripts_common.sh

Branches:
* master
* one-5.6-devel
* one-5.6

B #1955 Produce source xml for all given hosts

---

src/sunstone/etc/sunstone-views/kvm/admin.yaml
src/sunstone/etc/sunstone-views/kvm/groupadmin.yaml
src/sunstone/etc/sunstone-views/kvm/user.yaml
src/sunstone/etc/sunstone-views/mixed/admin.yaml
src/sunstone/etc/sunstone-views/mixed/groupadmin.yaml
src/sunstone/etc/sunstone-views/mixed/user.yaml
src/sunstone/etc/sunstone-views/vcenter/admin.yaml
src/sunstone/etc/sunstone-views/vcenter/groupadmin.yaml
src/sunstone/etc/sunstone-views/vcenter/user.yaml
src/sunstone/public/app/sunstone-config.js
src/sunstone/public/app/tabs/hosts-tab/datatable.js
src/sunstone/public/app/utils/dashboard.js

F #2600: Added key into yamls to disable dashboard count animation

---

src/oca/ruby/opennebula/virtual_machine.rb

B #2610: save as template treats iso cds

B #2610: vm saveas works with CDs

---

src/tm_mad/vcenter/mvds
src/vmm_mad/remotes/lib/vcenter_driver/datastore.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb

B #2624: [vCenter] persistency works with unmanaged disks

---

src/vnm/VirtualNetwork.cc

do not check vcenter_net_ref at net creation

---

src/sunstone/public/app/tabs/secgroups-tab/utils/common.js

B #2580 Sunstone is not showing well security groups for ICMP6

---

src/vmm_mad/remotes/lib/lxd/mapper/mapper.rb
src/vmm_mad/remotes/lib/lxd/mapper/qcow2.rb
src/vmm_mad/remotes/lib/lxd/opennebula-lxd

Fix bugs detected with microenvs testing

Feature 1684 fix2

---

src/image/Image.cc
src/rm/RequestManagerClone.cc
src/tm_mad/vcenter/delete
src/tm_mad/vcenter/mvds
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb
src/vmm_mad/remotes/vcenter/deploy

[vcenter] instantiate as persistent, reduce overhead, starting bootOrder

---

src/datastore_mad/remotes/vcenter/clone
src/vmm_mad/remotes/lib/vcenter_driver/datastore.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

some vCenter fixes and  clone CD-roms

---

src/oca/go/src/goca/cluster.go
src/oca/go/src/goca/datastore.go
src/oca/go/src/goca/group.go
src/oca/go/src/goca/host.go
src/oca/go/src/goca/user.go
src/oca/go/src/goca/vdc.go
src/oca/go/src/goca/virtualnetwork.go
src/oca/go/src/goca/zone.go

This pull request fix the Info method of the host in host.go file from go bindings

B #2658: GOCA - fix Info methods

---

src/oca/go/src/goca/goca.go
src/oca/go/src/goca/marketplace.go
src/oca/go/src/goca/marketplaceapp.go
src/oca/go/src/goca/securitygroup.go
src/oca/go/src/goca/virtualrouter.go

This pull request implements missing XML RPC in Goca:
* security group
* marketplace
* marketplace app
* virtual router
* system config

F #2656: [GOCA] add missing XML RPC Go Bindings

---

src/oca/go/src/goca/helper_test.go
src/oca/go/src/goca/image_test.go
src/oca/go/src/goca/marketplace.go
src/oca/go/src/goca/marketplace_test.go
src/oca/go/src/goca/marketplaceapp.go
src/oca/go/src/goca/securitygroup.go
src/oca/go/src/goca/securitygroup_test.go
src/oca/go/src/goca/virtualnetwork.go
src/oca/go/src/goca/virtualnetwork_test.go

Fix Chown for:
- MarketPlace
- MarketPlaceApp
- SecurityGroup
+ Fix CreateVirtualNetwork call to fit the Go syntax

B #2690: Fix wrong Chown helpers + add some tests

---

src/oca/go/src/goca/goca.go

Fix previous error I made on types

B #2678: GOCA - fix type errors

---

src/sunstone/etc/sunstone-views/kvm/admin.yaml
src/sunstone/etc/sunstone-views/kvm/groupadmin.yaml
src/sunstone/etc/sunstone-views/kvm/user.yaml
src/sunstone/etc/sunstone-views/mixed/admin.yaml
src/sunstone/etc/sunstone-views/mixed/groupadmin.yaml
src/sunstone/etc/sunstone-views/mixed/user.yaml
src/sunstone/etc/sunstone-views/vcenter/admin.yaml
src/sunstone/etc/sunstone-views/vcenter/groupadmin.yaml
src/sunstone/etc/sunstone-views/vcenter/user.yaml
src/sunstone/public/app/tabs/datastores-tab/actions.js
src/sunstone/public/app/tabs/vnets-tab/actions.js
src/sunstone/public/app/tabs/vnets-tab/dialogs/add-ar.js
src/sunstone/public/app/tabs/vnets-templates-tab.js
src/sunstone/public/app/tabs/vnets-templates-tab/actions.js
src/sunstone/public/app/tabs/vnets-templates-tab/buttons.js
src/sunstone/public/app/tabs/vnets-templates-tab/dialogs/add-ar.js
src/sunstone/public/app/tabs/vnets-templates-tab/dialogs/add-ar/dialogId.js
src/sunstone/public/app/tabs/vnets-templates-tab/dialogs/instantiate-add-ar.js
src/sunstone/public/app/tabs/vnets-templates-tab/dialogs/update-ar/dialogId.js
src/sunstone/public/app/tabs/vnets-templates-tab/form-panels/create.js
src/sunstone/public/app/tabs/vnets-templates-tab/form-panels/instantiate.js
src/sunstone/public/app/tabs/vnets-templates-tab/form-panels/instantiate/templateRow.hbs
src/sunstone/public/app/tabs/vnets-templates-tab/panels/ar.js
src/sunstone/public/app/tabs/vnets-templates-tab/panels/template/html.hbs
src/sunstone/public/app/tabs/vnets-templates-tab/panels/template/panelId.js
src/sunstone/public/app/tabs/vnets-templates-tab/panels/templates.js
src/sunstone/public/app/utils/dialogs/clusters.js

F #826: Fixed Sunstone bugs

---

src/tm_mad/qcow2/cpds

To get over mystery permission-denied error

B #2646 Touch DST before blockcopy

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/context.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/general.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/network.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/os.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/os/html.hbs
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/storage.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/vmgroup.js

F #2652: Allow boot order for vcenter in Sunstone

---

src/sunstone/public/app/tabs/vnets-tab/buttons.js

Change instantiate and import buttons in order to be cohesive

---

src/oca/go/src/goca/cluster.go
src/oca/go/src/goca/datastore.go
src/oca/go/src/goca/group.go
src/oca/go/src/goca/host.go
src/oca/go/src/goca/user.go
src/oca/go/src/goca/vdc.go
src/oca/go/src/goca/virtualnetwork.go
src/oca/go/src/goca/zone.go

Errors returned by the call in Info method were not checked

B #2658: GOCA - fix missing error check in Info methods

---

src/oca/go/src/goca/goca.go

This add the parsing of the error code from the opennebula reponse and return it to the user.
It allow a fine grained error management

B #2678 GOCA - parse error code of the ONe response

---

src/sunstone/public/app/tabs/templates-tab/buttons.js
src/sunstone/public/app/tabs/vnets-templates-tab/buttons.js

Splited sunstone button instantiate and create for templates

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

Fix model problems with vcenter

---

src/sunstone/public/app/utils/dialogs/clusters.js

Fixed bug with clusters button

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

Co-authored-by: semedi <ssemedi@opennebula.systems>
Apply to:
- master

Improve code for vcenter nic model

---

src/oca/go/src/goca/image_test.go
src/oca/go/src/goca/marketplace_test.go
src/oca/go/src/goca/marketplaceapp_test.go
src/oca/go/src/goca/securitygroup_test.go
src/oca/go/src/goca/template_test.go
src/oca/go/src/goca/virtualnetwork_test.go
src/oca/go/src/goca/virtualrouter_test.go

Fix GOCA tests: fix compilation and fix unexpected behavior

 B #2756: GOCA - fix tests

---

src/oca/go/src/goca/host.go

Add states methods for returning value and string related to the XML STATE field of the host

F #2759: GOCA - add states methods for the host

---

install.sh
share/websockify/run
share/websockify/websockify
share/websockify/websockify/__init__.py
share/websockify/websockify/auth_plugins.py
share/websockify/websockify/token_plugins.py
share/websockify/websockify/websocket.py
share/websockify/websockify/websocketproxy.py
src/sunstone/OpenNebulaVNC.rb

release v0.8.0
https://github.com/kanaka/websockify.git

F #1012: update websockify to latest version

---

src/datastore_mad/remotes/libfs.sh

* There still might be hosts which are part of Ceph cluster but not OpenNebula
* The host might be added afterwards

B #1136 Filter out only hosts which are off, disabled or error

---

share/etc/oned.conf
src/vmm/LibVirtDriverKVM.cc
src/vmm_mad/remotes/kvm/deploy
src/vmm_mad/remotes/kvm/kvmrc
src/vmm_mad/remotes/kvm/snapshot_create
src/vmm_mad/remotes/kvm/snapshot_delete

tests: https://github.com/OpenNebula/development/pull/497

F #2095 Support persistent VM snapshots for kvm

---

src/vmm_mad/remotes/lib/lxd/command.rb
src/vmm_mad/remotes/lib/lxd/mapper/qcow2.rb
src/vmm_mad/remotes/lib/lxd/mapper/rbd.rb

rbd-nd also has delays like rbd-nbd on Linux at showing the partition table when mapping

Feature 1684

---

src/authm_mad/remotes/server_cipher/server_cipher_auth.rb
src/authm_mad/remotes/server_x509/server_x509_auth.rb
src/cloud/common/CloudAuth/OpenNebulaCloudAuth.rb
src/sunstone/sunstone-server.rb
src/um/UserPool.cc

authenticates with a scoped user token

B #2575: encode the EGID in the authentication token when a user

---

src/vmm_mad/remotes/lib/lxd/mapper/rbd.rb

Removed not required multipart check.

F #1684: Fix trymount

---

src/oca/go/src/goca/cluster.go
src/oca/go/src/goca/datastore.go
src/oca/go/src/goca/group.go
src/oca/go/src/goca/host.go
src/oca/go/src/goca/image.go
src/oca/go/src/goca/marketplace.go
src/oca/go/src/goca/marketplaceapp.go
src/oca/go/src/goca/securitygroup.go
src/oca/go/src/goca/template.go
src/oca/go/src/goca/user.go
src/oca/go/src/goca/vdc.go
src/oca/go/src/goca/virtualnetwork.go
src/oca/go/src/goca/virtualrouter.go
src/oca/go/src/goca/vm.go
src/oca/go/src/goca/vntemplate.go
src/oca/go/src/goca/zone.go

This pull request provide two major fixes to the encoding/xml package migration:
* Info method struct cleaning
* remove some mutualized part among structs, it cost a bit more of memory but the code is less tricky

F #2830: GOCA - provide some fixes

---

src/vmm_mad/exec/one_vmm_exec.rb
src/vnm_mad/one_vnm.rb
src/vnm_mad/remotes/802.1Q/clean
src/vnm_mad/remotes/802.1Q/post
src/vnm_mad/remotes/802.1Q/pre
src/vnm_mad/remotes/802.1Q/update_sg
src/vnm_mad/remotes/bridge/clean
src/vnm_mad/remotes/bridge/pre
src/vnm_mad/remotes/ebtables/clean
src/vnm_mad/remotes/ebtables/post
src/vnm_mad/remotes/ebtables/pre
src/vnm_mad/remotes/ebtables/update_sg
src/vnm_mad/remotes/fw/clean
src/vnm_mad/remotes/fw/post
src/vnm_mad/remotes/fw/pre
src/vnm_mad/remotes/fw/update_sg
src/vnm_mad/remotes/ovswitch/clean
src/vnm_mad/remotes/ovswitch/post
src/vnm_mad/remotes/ovswitch/pre
src/vnm_mad/remotes/ovswitch_vxlan/clean
src/vnm_mad/remotes/ovswitch_vxlan/post
src/vnm_mad/remotes/ovswitch_vxlan/pre
src/vnm_mad/remotes/vxlan/clean
src/vnm_mad/remotes/vxlan/post
src/vnm_mad/remotes/vxlan/pre
src/vnm_mad/remotes/vxlan/update_sg

- xml is passed instead through STDIN
- ARGV[0] is now deploy id

#2851: Send network drivers xml via STDIN

---

.github/stale.yml

F #3012: Add stale bot conf file

---

src/market/MarketPlaceAppPool.cc

B #3017: Init map if the app must be deleted

---

src/vmm_mad/remotes/lib/lxd/client.rb
src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lib/lxd/opennebula_vm.rb

- Add snap patch for VNC
- Replace try and error method by socket location
Fixes #3069

Update lxc exec

---

SConstruct
include/Nebula.h

To be squashed and cherry-picked into one-5.8

F #3016: Add git version into oned -v

---

src/market_mad/remotes/linuxcontainers/monitor

- Applies to master and 5.8.1
- Reduced LXD market monitor execution time

B #3014 Reduce TCP connections to linuxcontainers.org

---

src/vmm_mad/remotes/lib/lxd/mapper/mapper.rb

As a side note, this issue could happen again in the context of a non-persisten multiple partition image with xfs filesystems
Fixes #3103

Fix XFS uuid mount related issues 

---

src/vmm_mad/remotes/lib/lxd/client.rb
src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lib/lxd/opennebula_vm.rb
src/vmm_mad/remotes/lxd/deploy

Fix LXD storage errors on deploy start action error handling

---

src/sql/LogDB.cc

Improve setup_index query

---

include/ScheduledAction.h
src/scheduler/include/VirtualMachinePoolXML.h
src/scheduler/src/sched/Scheduler.cc
src/vm_template/ScheduledAction.cc

* Change next_action to return the time for next_action
* Change XML query to use REPEAT
* Update the TIME if the value is lower than DONE

B #3119: Hourly sched actions just execute one time

---

src/oca/go/src/goca/host.go
src/oca/go/src/goca/vm.go

F #3144 monitoring methods should return the monitoring info

---

src/cli/one_helper/oneprovision_helper.rb
src/cli/oneprovision
src/oneprovision/lib/provision.rb

* Increase the default timeout from 10 to 20
* Add cleanup_timeout parameter to configure it via CLI
* Implement wait_image_delete, to wait until images are deleted

B #3136: timeout when using cleaunp option

---

src/vmm_mad/remotes/lib/lxd/mapper/mapper.rb
src/vmm_mad/remotes/lib/lxd/mapper/qcow2.rb
src/vmm_mad/remotes/lib/lxd/mapper/rbd.rb

Improve LXD mappers wait for multipart  condition

---

src/oca/go/src/goca/errors.go

F #3149 API error codes missed in GOCA

---

src/oca/go/src/goca/template.go
src/oca/go/src/goca/template_test.go
src/oca/go/src/goca/vm_test.go

F #3151 Add clone parameter to template instantiate function

---

src/oca/go/src/goca/cluster.go
src/oca/go/src/goca/host.go
src/oca/go/src/goca/marketplaceapp.go
src/oca/go/src/goca/quota.go
src/oca/go/src/goca/template.go
src/oca/go/src/goca/virtualnetwork.go
src/oca/go/src/goca/vm.go

It imply some small breaking changes.
It also fix some golint problems.

F #2830: GOCA - fix inconsistent xml mapped names

---

src/sunstone/public/app/tabs/marketplaceapps-tab/form-panels/export.js
src/sunstone/public/app/tabs/marketplaceapps-tab/form-panels/export/wizard.hbs

This PR applies to:
* master
* one-5.8

B #3066 no show datatables if type is a VMTEMPLATE

---

src/sunstone/public/app/app.js
src/sunstone/sunstone-server.rb

Signed-off-by: Jorge Lobo <jlobo@opennebula.systems>
This PR applies to:
master
one-5.8.1

B #3157 ZONE_NAME header gets stripped by passenger

---

src/sunstone/public/app/app.js
src/sunstone/public/app/opennebula.js
src/sunstone/public/app/opennebula/action.js
src/sunstone/public/app/opennebula/support.js
src/sunstone/public/app/sunstone-config.js
src/sunstone/public/app/sunstone.js
src/sunstone/public/app/tabs/groups-tab/panels/info.js
src/sunstone/public/app/tabs/settings-tab.js
src/sunstone/public/app/tabs/settings-tab/panels/user-config.js
src/sunstone/public/app/tabs/support-tab.js
src/sunstone/public/app/tabs/support-tab/actions.js
src/sunstone/public/app/tabs/support-tab/title.hbs
src/sunstone/public/app/tabs/support-tab/utils/common.js
src/sunstone/public/app/tabs/users-tab/actions.js
src/sunstone/public/app/tabs/users-tab/dialogs/login-token.js
src/sunstone/public/scss/_layout.scss
src/sunstone/public/scss/_menu.scss
src/sunstone/public/scss/_provision.scss
src/sunstone/routes/support.rb
src/sunstone/views/index.erb

This PR applies to:
* master
* one-5.8.1

Feature 3167

---

src/sunstone/public/app/app.js
src/sunstone/sunstone-server.rb

this PR apply
-one-5.8
-master

B #3157 ZONE-NAME header gets stripped by sinatra

---

src/sunstone/public/app/tabs/groups-tab/form-panels/create/wizard.hbs
src/sunstone/public/app/tabs/images-tab/form-panels/create/wizard.hbs

this PR apply
-master
-one-5.8

B #3018 Creating persistent image via sunstone

---

share/linters/.rubocop.yml
src/onedb/fsck.rb
src/onedb/fsck/quotas.rb

* Add function to calculate running quotas
* Divide the code in small functions
* Refactor some code

B #3082: FSCK doesn't update running quotas

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

B OpenNebula/one#3134 Fix check poweroff status

---

share/linters/.rubocop.yml
src/onedb/fsck/network.rb

* Divide the code into functions
* Fix some bugs
* Lint the code

F #3263: Simplify and make the FSCK network code more clear

---

src/host/HostShare.cc
src/lcm/LifeCycleActions.cc
src/lcm/LifeCycleStates.cc
src/rm/RequestManagerVirtualMachine.cc

B #3230 Wrong PCI to VM association removed when migrating VM with PCI pass-through

---

src/sunstone/public/app/opennebula/vm.js
src/sunstone/public/app/tabs/support-tab/title.hbs

this PR apply:
-master
-one-5.8

B #3213 Adjust Sunstone banner

---

src/oca/ruby/opennebula/virtual_machine_pool.rb
src/sunstone/models/SunstoneServer.rb

New Sunstone attribute to pull extended pool info from oned
Signed-off-by: Jorge Lobo <jlobo@opennebula.systems>

B #3308: Extended info conf attribute

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

B #3281: import wild vms default to host 0

---

src/tm_mad/ceph/monitor

F #3222: return ec pool usage if used

---

src/sunstone/public/app/utils/vcenter/clusters.js

this PR apply:
-one-5.8
-master

B #3280: check import vcenter cluster

---

src/onedb/fsck/vm.rb

B #3362: count NIC aliases in onedb fsck

---

src/sunstone/public/app/tabs/marketplaceapps-tab/form-panels/export.js
src/sunstone/public/app/tabs/marketplaceapps-tab/form-panels/export/wizard.hbs

this PR apply:
-one-5.8
-master

B #3368:  missing datastores import market

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine_device/vm_disk.rb

Change remaining is_cd? calls in virtual_machine.rb and vm_disk.rb
Also changed on vcenter-13-VM_Save_spec.rb and
vcenter-97-Add_New_Disk.rb files

L #3264: Corrections over last linting

---

src/onegate/onegate-server.rb

* Add comparation between two integers

B #2047: onegate error when trying to poweroff a VM

---

src/authm_mad/remotes/ldap/ldap_auth.rb

Fixes #3366.
I also wanted to update the docs but could not find them in the repo.
If you point me at the repo/place where they live I can also update those.

F #3366: allow alternative search base for ldap groups

---

src/sunstone/public/app/tabs/hosts-tab/panels/wilds.js

this PR apply:
-master
-one-5.8

B #3057: missing DEPLOY_ID import vcenter

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/os.js

this PR apply:
-master
-one-5.8

B #3101: multiple entries conf VM

---

src/sunstone/public/app/opennebula/template.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

this PR apply:
-one-5.8
-master

Bug 3195 remove OPENNEBULA_MANAGED attribute

---

src/cli/etc/onezone.yaml

F #3378: add fed_index column to config file

---

src/sunstone/etc/sunstone-server.conf

B #3428: fix bug lost icons VNC in federation

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

this PR apply:
-master
-one-5.8

Bug 3335: add select default zone endpoint

---

src/sunstone/public/bower.json

Signed-off-by: Vlastimil Holer <vholer@opennebula.systems>

B #3451: Sunstone git dependencies

---

src/vmm_mad/remotes/lib/vcenter_driver/host.rb

This is for merge with master and one-5.8

F #3438: show if DRS is enabled in vCenter

---

src/vmm_mad/remotes/lib/vcenter_driver/host.rb

This is for merge with master and one-5.8

F #3438: show if vCenter cluster have activated HA

---

src/cli/cli_helper.rb

F #688: fix bug in CLI top

---

src/datastore_mad/remotes/vcenter/rm

B #3463: fix error when delete image on vcenter using nfs

---

src/oca/ruby/opennebula/marketplaceapp.rb

B #3444: fix errr when import a qcow2 app into a vmdk ds

---

src/datastore_mad/remotes/vcenter/rm

Merge with master and one-5.8
Wrong var name in vcenter/rm 

M #~: wrong var name

---

src/cli/onevcenter

B #3439: polish onevcenter tool

---

src/vmm_mad/remotes/lib/vcenter_driver/datacenter.rb
src/vmm_mad/remotes/lib/vcenter_driver/network.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb

Support to:
Import Opaque Networks
Import Templates with Opaque Networks
Import Wild VMs with Opaque Networks
Attach/Detach Opaque Network nics
Poweron/Poweroff.. Instances with Opaque Networks

F #3440: Added basic support to Opaque Networks

---

src/sunstone/public/app/sunstone.js
src/sunstone/public/app/tabs/images-tab/dialogs/clone.js
src/sunstone/public/app/tabs/vnets-tab/actions.js
src/sunstone/public/app/utils/dialogs/clusters.js
src/sunstone/public/app/utils/notifier.js

this PR apply:
-master
-one-5.8

B #3217 Create or update a virtual network  in sunstone

---

src/sunstone/views/login.erb

B #2497: two factor authentication

---

src/vmm_mad/remotes/lib/vcenter_driver/vcenter_importer.rb

B #3439: polish onevcenter tool, second

---

src/vmm_mad/remotes/vcenter/deploy

F #1302: improve error messages on vcenter deploy

---

share/linters/.rubocop.yml
src/vmm_mad/remotes/vcenter/deploy

L #~: linting code of vcenter

---

src/market_mad/remotes/linuxcontainers/monitor

Configurable LXD marketplace app exclusion.

F #3467: Filter tested apps

---

src/vm/VirtualMachine.cc

B #3513 Fix AUTOMATIC_DS_REQUIREMENTS  

---

include/ImageManager.h
share/etc/oned.conf
src/image/ImageManager.cc
src/image/ImageManagerDriver.cc
src/nebula/Nebula.cc
src/nebula/NebulaTemplate.cc
src/tm_mad/fs_lvm/monitor
src/tm_mad/shared/monitor

Tested with qcow2
Code for fs_lvm DS is same, but I was unable to test it
Not implemented for ssh DS, as the monitor action there is a lot different

F #2765: Configurable VM disk monitoring

---

include/VirtualMachinePool.h
src/vm/VirtualMachine.cc
src/vm/VirtualMachineContext.cc
src/vm/VirtualMachinePool.cc

B #3484: add DETACH=YES in context.sh

---

src/sunstone/models/OpenNebula2FA/sunstone_2f_auth.rb
src/sunstone/models/OpenNebulaJSON/UserJSON.rb
src/sunstone/sunstone-server.rb

B #2497: fix request sunstone_2f_auth

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/general.js

this PR apply:
-master
-one-5.8

B #3435: remove option by mode

---

src/sunstone/public/app/tabs/vmgroup-tab/datatable.js

B #3336: fix bug undefined position

---

src/sunstone/public/app/tabs/vnets-tab/panels/ar.js

this PR apply:
-master
-one-5.8

B #3221: fix bug desappear rm_ar_button

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

this PR apply:
-master
-one-5.8

B #3195: fix bug position elements

---

src/cli/etc/oneprovision.yaml

M #: oneprovision command expand column name

---

src/oca/go/src/goca/client.go

Follow breaking changes made in external xmlrpc package used by goca

B #3546: GOCA - follow xmlrpc module changes

---

src/sunstone/public/app/tabs/hosts-tab/panels/numa.js

this PR apply:
-master
-one-5.8

B #3254: fix bug hugepages

---

src/sunstone/public/app/tabs/hosts-tab/panels/numa.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/numa.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/numa/html.hbs
src/sunstone/public/scss/_settings.scss
src/sunstone/public/scss/_table.scss

F #3254: add isolcpus

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/numa.js

B #3254: add function parse  hugepage

---

src/sunstone/public/app/tabs/vms-tab/utils/state-actions.js

F #1764: active button VM.updateconf

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

this PR apply:
-master
-one-5.8

B #3195: lost action

---

src/vnm_mad/remotes/lib/security_groups_iptables.rb

Signed-off-by: Venko Moyankov <vmoyankov@gmail.com>

B #3556: Fix IP spoofing filters

---

share/install_gems/Debian10/Gemfile.lock

To be merged just into master.

F #3576: Gemfile.lock for Debian 10

---

src/vmm_mad/remotes/lib/vcenter_driver/host.rb

F #3440: Fix hash syntax

---

src/cli/one_helper/onevm_helper.rb
src/cli/onevm

Analogous to the VM snapshot argument.

B #3496: Validate disk-snapshot id

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine_monitor/vm_monitor.rb
src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb

Fix the problem when trying to import a VM with
guest.net.ipConfig attribute unset.

B #3563: Fix VM import

---

install.sh
share/hooks/alias_ip/alias_ip.rb
share/linters/.rubocop.yml
share/vendor/ruby/gems/packethost/lib/packet/client.rb
share/vendor/ruby/gems/packethost/lib/packet/client/ip_ranges.rb
share/vendor/ruby/gems/packethost/lib/packet/client/ips.rb
share/vendor/ruby/gems/packethost/lib/packet/device.rb
share/vendor/ruby/gems/packethost/lib/packet/ip.rb
share/vendor/ruby/gems/packethost/lib/packet/ip_range.rb
src/ipamm_mad/remotes/packet/allocate_address
src/ipamm_mad/remotes/packet/free_address
src/ipamm_mad/remotes/packet/get_address
src/ipamm_mad/remotes/packet/register_address_range
src/ipamm_mad/remotes/packet/unregister_address_range
src/vmm_mad/remotes/packet/packet_driver.rb
src/vnm_mad/remotes/alias_sdnat/AliasSDNAT.rb
src/vnm_mad/remotes/alias_sdnat/clean
src/vnm_mad/remotes/alias_sdnat/post
src/vnm_mad/remotes/alias_sdnat/pre
src/vnm_mad/remotes/alias_sdnat/update_sg

Do not squash the commits, they have been squashed previously.

 F #3042: Packet Public Networking

---

src/cli/oneimage
src/cli/onesecgroup
src/cli/onetemplate
src/cli/onevmgroup
src/cli/onevntemplate
src/cli/onevrouter

M #~: fixing some typos

---

src/docker_machine/src/docker_machine/Gopkg.lock
src/docker_machine/src/docker_machine/Gopkg.toml
src/docker_machine/src/docker_machine/opennebula.go

with new GOCA 
Applies to:
master

M #-: Fix docker-machine addon compatibility

---

share/hooks/alias_ip/alias_ip.rb
src/ipamm_mad/remotes/packet/allocate_address
src/ipamm_mad/remotes/packet/free_address
src/ipamm_mad/remotes/packet/get_address
src/ipamm_mad/remotes/packet/register_address_range
src/ipamm_mad/remotes/packet/unregister_address_range
src/vnm_mad/remotes/alias_sdnat/clean
src/vnm_mad/remotes/alias_sdnat/clean.d/.gitignore
src/vnm_mad/remotes/alias_sdnat/post
src/vnm_mad/remotes/alias_sdnat/post.d/.gitignore
src/vnm_mad/remotes/alias_sdnat/pre.d/.gitignore

Adapts code to
- new dedicated gems locations
- new way of passing vnet drivers data over stdin instead of argument
To be merged just into **master**.

F #3042: Respect GEMS_LOCATION, use STDIN for data

---

src/parsers/vm_var_syntax.y

B #3578: change parser to process alias

---

src/cli/one_helper.rb

Capture exception when quitting from pager, so it doesn't show any error

B #3628: fix xml paginated list bug

---

src/cli/oneflow-template

B #3607: fix oneflow-template show output format

---

src/sunstone/public/app/console/vnc.js
src/sunstone/public/app/utils/vnc.js

this PR apply: 
-master
-one-5.8

B #3597: fix VNC with VN password enable

---

src/sunstone/public/bower.json

this PR apply
-master
-one-5.8

B #3590: change package vnc for git

---

src/sunstone/public/app/tabs/provision-tab.js

this PR apply:
-master
-one-5.8

B #3120: get number groups by VM

---

src/sunstone/public/app/tabs/vmgroup-tab/panels/info/html.hbs

this PR Apply:
-master
-one-5.8

B #3599: rename affinity by VM Affinity

---

src/sunstone/public/app/tabs/vms-tab/panels/network.js

this PR apply:
-master
-one-5.8-maintenance

B #3241: show ipv6 address

---

src/sunstone/public/bower.json

this PR apply:
-master
-one-5.8

B #3590: fixed to version commit novnc

---

share/linters/.rubocop.yml
src/cli/etc/oneacl.yaml
src/cli/one_helper/oneacl_helper.rb
src/cli/oneacl

F #3863: show raw ACL string

---

src/sunstone/public/app/tabs/vms-tab/utils/state-actions.js

this PR apply:
-master
-one-5.8

F #3441: add reschedule in poweroff sunstone

---

include/Request.h
src/hem/onehem-server.rb
src/hm/HookAPI.cc
src/rm/RequestManagerAllocate.cc
src/rm/RequestManagerDelete.cc

The object of the body will be returned for allocate and delete calls.

F #3380: return object body on API hooks

---

src/sunstone/public/app/tabs/vnets-tab/panels/info.js
src/sunstone/public/app/tabs/vnets-templates-tab/panels/info.js

this PR apply:
-master
-one-5.8

B #3087: show vCenter id in VLAN

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/storage.js

this PR apply:
-master
-one-5.8

B #3303: save deploy mode

---

src/vnm_mad/remotes/802.1Q/vlan_tag_driver.rb
src/vnm_mad/remotes/lib/no_vlan.rb
src/vnm_mad/remotes/ovswitch/OpenvSwitch.rb
src/vnm_mad/remotes/ovswitch_vxlan/OpenvSwitchVXLAN.rb
src/vnm_mad/remotes/vxlan/vxlan.rb

Introduced by improper linting.

B #3613: Fix all occurrences of renamed methods

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/os.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/os/html.hbs

F #2587: add select SD_DISK_BUS sunstone

---

share/etc/oned.conf
share/hooks/alias_ip/alias_ip.rb
src/ipamm_mad/remotes/packet/allocate_address
src/ipamm_mad/remotes/packet/free_address
src/ipamm_mad/remotes/packet/get_address
src/ipamm_mad/remotes/packet/register_address_range
src/ipamm_mad/remotes/packet/unregister_address_range
src/oneprovision/lib/utils.rb
src/vmm_mad/remotes/packet/packet_driver.rb

* Remove en/decryption from Packet IPAM drivers
* Remove en/decryotion from alias hook
* Remove en/decryotion from Packet driver

F #3064: adapt DDC to new secrets handling

---

src/oneprovision/lib/provision.rb
src/oneprovision/lib/resource.rb
src/oneprovision/lib/vnet.rb

This reverts commit c2ff7f89d85e9245861eb098a72eb6925110478b.

B #3070: revert DDC temporal solution

---

share/hooks/vcenter/create_vcenter_net.rb
share/hooks/vcenter/delete_vcenter_net.rb

Change the way of get parameters due to new hooks system

M #-: Changes hook parameters

---

src/cli/onecluster
src/cli/onedatastore
src/datastore/Datastore.cc

* Add enrypt at insert in datastores
* Add option to decrypt cluster/datastore in CLI

F #3064: fix minor bugs

---

SConstruct

Merge after:
* https://github.com/OpenNebula/packages/pull/104
* https://github.com/OpenNebula/infra/pull/319

M #-: Allow passing GITVERSION as argument

---

src/cli/one_helper/onevcenter_helper.rb
src/cli/onevcenter
src/vmm_mad/remotes/lib/vcenter_driver/host.rb
src/vmm_mad/remotes/lib/vcenter_driver/vi_client.rb

F #1208: change the port used connects to vSphere

---

src/sunstone/routes/vcenter.rb

F #1208: add support for sunstone

---

src/cli/cli_helper.rb
src/cli/one_helper/onehook_helper.rb
src/cli/onehook
src/oca/ruby/opennebula/hook.rb
src/oca/ruby/opennebula/hook_log.rb

F #3380: add log subcommand to onehook

---

install.sh
share/examples/host_hooks/error_hook
src/cli/one_helper.rb
src/cli/onehook

* Fix minor bugs in onehook show command

F #3380: add host error hook template example

---

share/augeas/oned.aug

+ https://github.com/OpenNebula/packages/pull/105

F #3741: Augeas lens for oned.conf

---

src/sunstone/public/app/sunstone.js
src/sunstone/public/app/tabs/marketplaceapps-tab/buttons.js

B #2728: button tooltips

---

src/sunstone/public/app/tabs/hosts-tab/actions.js
src/sunstone/public/app/tabs/hosts-tab/panels/nsx.js
src/sunstone/public/app/utils/tab-datatable/search-input.hbs

F #3440: fix errors in NSX form credentials

---

share/hooks/ft/host_error.rb
src/cli/cli_helper.rb
src/cli/onehook

* Fix bug in cli helper base64? funcion
* Change the way to read host idi in host_error script

F #3380: fix minor bugs

---

src/vmm_mad/remotes/lib/nsx_driver/nsx_client.rb

Sunstone has problems to treat XML and JSON as response.

F #3440: Change XML response from NSX-V to JSON

---

src/oca/go/src/goca/virtualnetwork.go

B #3580: Returns the ID of the new reserved vnet

---

src/oca/go/src/goca/vmgroup.go

B #3622: Allow VM groups to be created by GOCA

---

src/sunstone/public/app/tabs/datastores-tab/actions.js

B #3594: change clusters in datastore's table

---

src/sunstone/public/app/opennebula/action.js
src/sunstone/public/app/sunstone.js
src/sunstone/public/app/tabs/templates-tab/actions-common.js

B #3715 stop multiple click to back button

---

src/oca/python/Makefile

Merge together with:
* https://github.com/OpenNebula/infra/pull/324
* https://github.com/OpenNebula/packages/pull/107
* https://github.com/OpenNebula/development/pull/753
* https://github.com/OpenNebula/docs/pull/783

F OpenNebula/packages#106: Run python3-setuptools

---

src/sunstone/public/app/utils/schedule_action.js

B #3109: fix first id sched action when is 0

---

src/sunstone/public/app/tabs/images-tab/form-panels/create/wizard.hbs
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/storage/disk-tab/options.hbs

B #2971: rename SCSI for SCSI/SATA

---

src/sunstone/public/app/tabs/clusters-tab/datatable.js
src/sunstone/public/app/tabs/vdcs-tab/form-panels/create.js
src/sunstone/public/app/tabs/vdcs-tab/panels/resources.js
src/sunstone/public/app/tabs/vdcs-tab/utils/resources-tab.js
src/sunstone/public/app/tabs/vdcs-tab/utils/resources-zone.js
src/sunstone/public/app/utils/tab-datatable.js

F #2623 remove resource from VDC

---

install.sh
src/vmm_mad/exec/one_vmm_exec.rb
src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lxd/cancel
src/vmm_mad/remotes/lxd/reboot
src/vmm_mad/remotes/lxd/reset
src/vmm_mad/remotes/lxd/shutdown
src/vnm_mad/remotes/lib/lxd_clean.rb

- container hard reboot wasn't working due to no having the regular reboot steps
- updated the hard reboot call from the vm scripts and the forced stop action

Network Hook patch for LXD

---

src/sunstone/etc/sunstone-views/kvm/admin.yaml
src/sunstone/etc/sunstone-views/kvm/cloud.yaml
src/sunstone/etc/sunstone-views/kvm/groupadmin.yaml
src/sunstone/etc/sunstone-views/kvm/user.yaml
src/sunstone/etc/sunstone-views/mixed/admin.yaml
src/sunstone/etc/sunstone-views/mixed/cloud.yaml
src/sunstone/etc/sunstone-views/mixed/groupadmin.yaml
src/sunstone/etc/sunstone-views/mixed/user.yaml
src/sunstone/etc/sunstone-views/vcenter/admin.yaml
src/sunstone/etc/sunstone-views/vcenter/cloud.yaml
src/sunstone/etc/sunstone-views/vcenter/groupadmin.yaml
src/sunstone/etc/sunstone-views/vcenter/user.yaml

Bug #3215: missing actions yamls

---

src/sunstone/public/app/utils/tab-datatable.js

F #2623: add icon

---

src/sunstone/public/app/tabs/vms-tab/panels/network.js

B #3358: sunstone lose NIC index

---

src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js

This PR apply:
-master
-one-5.8

B #3803: send requeriments instance template

---

src/sunstone/public/app/tabs/oneflow-services-tab/datatable.js
src/sunstone/public/app/tabs/oneflow-templates-tab/datatable.js

B #1400: change order table services

---

src/sunstone/public/app/tabs/vnets-templates-tab/form-panels/create.js
src/sunstone/public/app/utils/panel/template-table.js

B  #3753: send context in VN template

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/context/html.hbs

B #1375: remove vm_updateconf_hide class in file_ds

---

share/pkgs/sudoers/centos/opennebula
share/pkgs/sudoers/debian/opennebula
share/sudoers/sudoers.rb

To be merged into
- ONE master

B #3046: Enable HA HEM server control and IP cmd

---

share/hooks/vcenter/create_vcenter_net.rb
src/vmm_mad/remotes/lib/nsx_driver/opaque_network.rb
src/vmm_mad/remotes/lib/nsx_driver/virtual_wire.rb

Fix bug when creating NSX network without
transport zone. Added more checks and
exceptions to manage them.

F #3440: Fix bug creating NSX networks

---

src/sunstone/public/app/tabs/hosts-tab/panels/numa.js

B #3254: Fix alignment table NUMA

---

src/tm_mad/shared/ln.ssh
src/tm_mad/shared/mvds.ssh

* reintroduce shared/mvds as mvds.ssh (deleted by mistake)
* adapt also shared/ln

B #3244: Fix mixed-modes for shared/ssh

---

share/hooks/vcenter/create_vcenter_net.rb

Remove rescue SystemExit
Apply unlock before each exit
Changes on some comments and debug lines

M #-: Modify hook exits

---

src/onedb/onedb_live.rb

- Applies to stable and master
- Fixes #3806

escape backslashes on onedb change-body 

---

src/sunstone/public/app/utils/vcenter/clusters.js
src/sunstone/routes/vcenter.rb

B #655: register hooks import host

---

src/cloud/common/CloudAuth/RemoteCloudAuth.rb
src/sunstone/etc/sunstone-server.conf

This PR allows to setup X-Auth-Username header for authenticate user:
fixes #3591

F #3591: Support X-Auth-Username header

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/io/html.hbs

M #-: remove hide class to password graphics

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

B #3832: preserve attributes vmtemplate

---

src/vmm_mad/remotes/lib/vcenter_driver/datacenter.rb
src/vmm_mad/remotes/lib/vcenter_driver/network.rb

B #3567: add switch name in DPG

---

src/vmm_mad/remotes/lib/vcenter_driver/datastore.rb
src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb

B #3818: fix Wild import in VMware

---

src/sunstone/public/app/sunstone.js
src/sunstone/public/scss/app.scss

B #3614: hide create button when no have option

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

B #3832: fill input Host Rank

---

src/vmm_mad/remotes/lib/vcenter_driver/host.rb

For non-NSX Clusters, nsx attributes was shown with
empty values, this changes that behaviour to show only
NSX_STATUS indicating Missing NSX_MANAGER.

B #3440: Fix bug on non-nsx clusters attributes

---

src/sunstone/public/app/tabs/vms-tab/dialogs/disk-resize.js

B # 3883: fix error on resize disk (firefox)

---

src/onedb/onedb_live.rb

B #3806: Use gsub escape

---

share/hooks/vcenter/create_vcenter_net.rb
src/vmm_mad/remotes/lib/nsx_driver/nsx_client.rb
src/vmm_mad/remotes/lib/nsx_driver/opaque_network.rb
src/vmm_mad/remotes/lib/nsx_driver/virtual_wire.rb

Added code to treat inputs in the creation network form
Puts errors on network creations in hook STDERR and in
VCENTER_NET_ERROR attribute.

F #3440: Added more input options and errors

---

src/vmm_mad/remotes/lib/vcenter_driver/datacenter.rb

Remove Distributed Port Groups uplinks from network detection
Remove networks without any host asociated.

B #3839: Fix remove DPG uplinks

---

src/cli/onevcenter
src/sunstone/routes/vcenter.rb
src/vmm_mad/remotes/lib/vcenter_driver/datacenter.rb
src/vmm_mad/remotes/lib/vcenter_driver/network.rb

B #3839: Added onevcenter list_all command
B #3839: Add filter to Sunstone

B #3839: onevcenter list_all and sunstone filter

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/os.js
src/sunstone/public/app/tabs/vms-tab/form-panels/updateconf.js
src/sunstone/public/app/utils/wizard-fields.js

B # 3858: update CPU model VM

---

share/examples/network_hooks/99-lxd_clean.rb

patch didn't consider if clean was being called by detach or shutdown, thus removing every host_side nic pair. Added a logic to detect hotplug action and clean only the hotplugged nic.

F #3189: Fix LXD net patch

---

share/install_gems/Gemfile
src/cloud/common/CloudClient.rb
src/oca/ruby/opennebula/oneflow_client.rb
src/sunstone/etc/sunstone-server.conf
src/sunstone/sunstone-server.rb

first step for no_proxy var

---

share/man/build.sh

Revert "F #3380: Generate man pages for onehook command"

---

src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lxd/deploy
src/vmm_mad/remotes/lxd/shutdown

F #3880: Save idmaps

---

src/sunstone/public/app/sunstone.js
src/sunstone/public/app/tabs/official-support-tab/actions.js

B #3268: lost requeriment

---

install.sh
src/vmm_mad/remotes/lib/nsx_driver/nsx_client.rb
src/vmm_mad/remotes/lib/nsx_driver/nsx_constants.rb
src/vmm_mad/remotes/lib/nsx_driver/nsxt_client.rb
src/vmm_mad/remotes/lib/nsx_driver/nsxt_tz.rb
src/vmm_mad/remotes/lib/nsx_driver/nsxv_client.rb
src/vmm_mad/remotes/lib/nsx_driver/nsxv_tz.rb
src/vmm_mad/remotes/lib/vcenter_driver/host.rb
src/vmm_mad/remotes/nsx/nsx_driver.rb

Refactor Transport Zones
Fix NSX_STATUS
Fix get transport zones

F #3440: Refactor Transport Zones and fixes

---

src/sunstone/public/locale/languages/cs_CZ.po
src/sunstone/public/locale/languages/da.po
src/sunstone/public/locale/languages/es_ES.po
src/sunstone/public/locale/languages/et_EE.po
src/sunstone/public/locale/languages/fr_FR.po
src/sunstone/public/locale/languages/ja.po
src/sunstone/public/locale/languages/nl_NL.po
src/sunstone/public/locale/languages/pt_BR.po
src/sunstone/public/locale/languages/pt_PT.po
src/sunstone/public/locale/languages/ru_RU.po
src/sunstone/public/locale/languages/sk_SK.po
src/sunstone/public/locale/languages/th_TH.po
src/sunstone/public/locale/languages/tr.po
src/sunstone/public/locale/languages/tr_TR.po
src/sunstone/public/locale/languages/zh_CN.po

M #-: update translations

---

src/sunstone/public/app/tabs/official-support-tab/actions.js
src/sunstone/public/app/tabs/official-support-tab/utils/common.js
src/sunstone/routes/support.rb
src/sunstone/sunstone-server.rb

B #3167: fix upgrade banner

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/vcenter/reboot
src/vmm_mad/remotes/vcenter/reset

B #3844: refactoring some functions

---

src/vmm_mad/remotes/lib/nsx_driver/nsx_constants.rb

Change HEADER_XML and HEADER_JSON format from { :key => 'value' }
to { 'key' => 'value' }

B #3440: Fix headers format

---

src/im_mad/remotes/node-probes.d/numa.rb

B #3972: fix bugs

---

src/oca/go/src/goca/acl.go
src/oca/go/src/goca/schemas/hook/template.go
src/oca/go/src/goca/schemas/image/image.go
src/oca/go/src/goca/schemas/vm/template.go
src/oca/go/src/goca/schemas/vm/usertemplate.go

- Fix method parameters type errors
- Remove dead code.
- Change image "Type" field type to string: allow to marshal image struct

B-3976 Fix small errors

---

src/oca/go/share/examples/ha_raft_status.go
src/oca/go/share/examples/vm_example.go
src/oca/go/share/examples/vm_get_by_name.go
src/oca/go/share/examples/vm_get_info.go
src/oca/go/src/goca/client.go
src/oca/go/src/goca/helper_test.go

F #3952: Changes GOCA NewClient to support a custom HTTP client

---

src/sunstone/routes/support.rb

B #3167: Fix bugs

---

src/sunstone/routes/support.rb

B #3167 remove version url curl git

---

src/market_mad/remotes/linuxcontainers/monitor

B #4005: Remove LXD URL quotes

---

src/sunstone/sunstone-server.rb

this PR apply:
- master
- one-5.10

B #3751: validate by APP_ENV

---

src/vmm_mad/remotes/kvm/restore
src/vmm_mad/remotes/kvm/snapshot_delete

And also redefine snapshot metadata also after the suspend/resume - not only stop/start.

B #4017: Redump VM snapshot xml after snap delete

---

src/vmm_mad/remotes/kvm/prereconfigure

F #4026: do not fail when CDROM already ejected

---

src/oca/python/pyone/util.py

Together with: https://github.com/OpenNebula/infra/pull/351

M #-: Adapt to latest generateDS

---

src/datastore_mad/remotes/lxd_downloader.sh

Applies to 5.8, 5.10 and master

F #4007: LXD Centos8 auto-context

---

share/linters/.rubocop.yml
src/onedb/onedb
src/onedb/onedb_live.rb

F #3999: add append option to onedb change-body

---

src/vnm_mad/remotes/lib/no_vlan.rb

Closes #4006 
Merge with https://github.com/OpenNebula/docs/pull/876
Applies to master as well

B #4006: Fix bridge clean

---

src/cli/command_parser.rb

F #-: add option to have multiple parameters in cmd

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/lib/vcenter_driver/vmm_importer.rb

B #3844: add references when import wilds

---

src/cli/one_helper/onevcenter_helper.rb
src/sunstone/routes/vcenter.rb
src/vmm_mad/remotes/lib/vcenter_driver/datacenter.rb

M #-: Refactor get_unimported_networks

---

src/datastore_mad/remotes/vcenter/mkfs

M #~: fix error in linting

---

src/datastore_mad/remotes/ceph/ceph_utils.sh

TOTAL = MAX_AVAIL + USED is wrong as MAX_AVAIL is already
number considering the replica mode. However, USED is total number
of data used on all replicas alltogether.
TOTAL = MAX_AVAIL + STORE is correct.

B #~: CEPH monitor pools correctly

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/vcenter/deploy

B #3844: second phase, sync when deploy

---

share/doc/xsd/acl_pool.xsd
share/doc/xsd/index.xsd

Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

#4076 Fixed XSD schema to include ACLs

---

src/oca/python/pyone/__init__.py
src/oca/python/pyone/acl.py

Rewrited from original Ruby code
Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

F #4078: Added OneAcl helper class to PyOne

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine_monitor/vm_monitor.rb

F #2771: add VM name on vCenter

---

src/tm_mad/vcenter/delete
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #1973: option for custom prefix and suffix in vm name

---

src/vmm_mad/remotes/lib/vcenter_driver/datacenter.rb

one_host variable was not updated in each iteration

M #-: Fix import network on multiple clusters

---

src/sunstone/views/_login_x509.erb

B #4096: fix login remote auth styles

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

This PR apply:
-master
-one-5.10

B #4112: fix hugepages numa in null create template

---

share/scripts/bash_completion.d/one

M #-: Add onetemplate to the bash_completition

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine_monitor/vm_monitor.rb

M #~: fix error in monitor script

---

src/oca/go/src/goca/schemas/shared/permissions.go

update Permissions structure fields types (without breaking changes)

[GOCA] permissions changes

---

src/oca/go/src/goca/schemas/cluster/template.go
src/oca/go/src/goca/schemas/datastore/template.go
src/oca/go/src/goca/schemas/hook/template.go
src/oca/go/src/goca/schemas/host/template.go
src/oca/go/src/goca/schemas/image/template.go
src/oca/go/src/goca/schemas/marketplace/template.go
src/oca/go/src/goca/schemas/marketplaceapp/template.go
src/oca/go/src/goca/schemas/securitygroup/rules.go
src/oca/go/src/goca/schemas/securitygroup/template.go
src/oca/go/src/goca/schemas/shared/disk.go
src/oca/go/src/goca/schemas/shared/nic.go
src/oca/go/src/goca/schemas/shared/quota.go
src/oca/go/src/goca/schemas/virtualnetwork/addressrange.go
src/oca/go/src/goca/schemas/virtualnetwork/template.go
src/oca/go/src/goca/schemas/virtualnetwork/virtualnetwork.go
src/oca/go/src/goca/schemas/virtualrouter/template.go
src/oca/go/src/goca/schemas/vm/template.go
src/oca/go/src/goca/schemas/vmgroup/vmgroup.go

- fix quota struct marshalling
- remove useless restriction on method parameters

[GOCA] template and struct fixes

---

src/sunstone/public/app/utils/status.js

B #3450: Fix highlighting states for images

---

src/sunstone/public/app/tabs/hosts-tab/panels/wilds.js

F #4131: Order wilds VMs in Sunstone

---

src/sunstone/public/app/console/vnc.js
src/sunstone/public/app/tabs/vms-tab/dialogs/vnc/html.hbs
src/sunstone/public/app/utils/vnc.js
src/sunstone/views/vnc.erb

B #4020: Fix status of NoVNC server

---

src/datastore_mad/remotes/fs/cp

B #4144: Fix error message

---

src/scheduler/include/VirtualMachineXML.h
src/scheduler/src/pool/VirtualMachineXML.cc
src/vm/VirtualMachinePool.cc

M #-: Fix memory leaks

---

share/install_gems/CentOS7/Gemfile.lock
share/install_gems/CentOS8/Gemfile.lock
share/install_gems/Debian10/Gemfile.lock
share/install_gems/Debian9/Gemfile.lock
share/install_gems/Gemfile
share/install_gems/Ubuntu1604/Gemfile.lock
share/install_gems/Ubuntu1804/Gemfile.lock
share/install_gems/Ubuntu1904/Gemfile.lock
share/install_gems/Ubuntu1910/Gemfile.lock
share/install_gems/install_gems
src/cli/one_helper/onezone_helper.rb
src/cli/onezone

Applies to 5.10 also.
**Do not squash commits**

F #4109: add onezone serversync command

---

src/onedb/fsck.rb
src/onedb/fsck/cluster.rb
src/onedb/fsck/datastore.rb
src/onedb/fsck/host.rb
src/onedb/fsck/image.rb
src/onedb/fsck/marketplaceapp.rb
src/onedb/onedb_backend.rb

B #4165: fix encoding for fsck

---

src/sunstone/public/app/tabs/users-tab/panels/info-common.js
src/sunstone/public/app/templates/helpers/valOrDefault.js
src/sunstone/public/app/utils/template-utils.js

this PR apply:
-master
-one-5.10

M #-: sanitize tags in handlebars forms

---

src/sunstone/public/app/tabs/vmgroup-tab/form-panels/create.js
src/sunstone/public/app/tabs/vmgroup-tab/utils/role-tab.js
src/sunstone/public/app/utils/template-utils.js

this PR apply:
-master
-one-5.10

M #-: xss in role name vmg

---

src/sunstone/public/app/opennebula/vm.js
src/sunstone/public/app/sunstone.js
src/sunstone/public/app/sunstone/buttons.hbs
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/network.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/network/nic-tab.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/network/nic-tab/html.hbs
src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js
src/sunstone/public/app/tabs/vms-tab/actions.js
src/sunstone/public/app/tabs/vms-tab/buttons.js
src/sunstone/public/app/tabs/vms-tab/hooks/state.js
src/sunstone/public/app/utils/nics-section.js
src/sunstone/public/app/utils/nics-section/dd.hbs
src/sunstone/public/app/utils/rdp.js

F #3969: Support for RDP links in sunstone

---

src/vmm_mad/remotes/lib/lxd/container.rb
src/vmm_mad/remotes/lxd/reboot
src/vmm_mad/remotes/lxd/shutdown

- Created a transient state method for monitoring purposes.
- Log poweroff action fail if LXD times out again.

Fix LXD state transitions

---

src/onedb/fsck/host.rb

M #: Fix linting

---

src/sunstone/public/app/tabs/hosts-tab/panels/wilds.js

F #4162: Increase number of paged wild VMs

---

src/sunstone/public/app/utils/tab-datatable.js

B #4153: Sanitize edit group dialog in sunstone

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

B #4178: Fix NIC alias in VM templates

---

src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js

B #4177: Fix VM scheduler requirements

---

src/sunstone/public/app/tabs/vnets-templates-tab/form-panels/create.js
src/sunstone/public/app/tabs/vnets-templates-tab/panels/clusters.js

B #4169: Fix clusters in VNet templates

---

src/sunstone/public/app/tabs/vnets-templates-tab/form-panels/create.js
src/sunstone/public/app/tabs/vnets-templates-tab/panels/clusters.js

M #~: Fix clusters on VNet Templates

---

src/tm_mad/vcenter/resize
src/vmm_mad/exec/one_vmm_sh
src/vmm_mad/remotes/vcenter/resize_disk

F #1542: vCenter hot disk resize

---

src/sunstone/public/css/custom.css

B #4083: Fix VNC window in Sunstone

---

src/cli/one_helper/oneimage_helper.rb

Applicable to master
Merge with https://github.com/OpenNebula/docs/pull/960

Remove oneimage create image path validation

---

src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js

M #~: Sanitize the code

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

B #4204: Fix template VMs in Sunstone

---

src/sunstone/public/app/tabs/vms-tab/dialogs/migrate.js

F #3194: Add datastore for live migration

---

src/cli/one_helper/oneimage_helper.rb

Moar Linting

---

src/sunstone/public/app/tabs/oneflow-templates-tab/utils/role-tab.js

B #4238: Fix vnets parameters in oneflow templates

---

src/sunstone/etc/sunstone-views/kvm/admin.yaml
src/sunstone/etc/sunstone-views/kvm/groupadmin.yaml
src/sunstone/etc/sunstone-views/kvm/user.yaml
src/sunstone/etc/sunstone-views/mixed/admin.yaml
src/sunstone/etc/sunstone-views/mixed/groupadmin.yaml
src/sunstone/etc/sunstone-views/mixed/user.yaml
src/sunstone/etc/sunstone-views/vcenter/admin.yaml
src/sunstone/etc/sunstone-views/vcenter/groupadmin.yaml
src/sunstone/etc/sunstone-views/vcenter/user.yaml
src/sunstone/public/app/tabs/oneflow-templates-tab/form-panels/create.js
src/sunstone/public/app/tabs/oneflow-templates-tab/form-panels/create/wizard.hbs
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/context.js
src/sunstone/public/app/utils/custom-tags-table.js
src/sunstone/public/bower.json

B #4132: remove values in vm template

---

src/sunstone/etc/sunstone-views/kvm/admin.yaml
src/sunstone/etc/sunstone-views/kvm/groupadmin.yaml
src/sunstone/etc/sunstone-views/kvm/user.yaml
src/sunstone/etc/sunstone-views/mixed/admin.yaml
src/sunstone/etc/sunstone-views/mixed/groupadmin.yaml
src/sunstone/etc/sunstone-views/mixed/user.yaml
src/sunstone/etc/sunstone-views/vcenter/admin.yaml
src/sunstone/etc/sunstone-views/vcenter/groupadmin.yaml
src/sunstone/etc/sunstone-views/vcenter/user.yaml

Signed-off-by: kvaps <kvapss@gmail.com>

B#~ Sunstone: Fix missing Network.instantiate_dialog

---

src/sunstone/public/app/utils/wizard-fields.js

B #4269: Fix retrieve input function

---

src/sunstone/public/app/tabs/oneflow-templates-tab/form-panels/create.js
src/sunstone/public/app/tabs/oneflow-templates-tab/utils/role-tab.js

B #4263: Fix form behavior in oneflow templates

---

src/sunstone/public/app/tabs/vnets-templates-tab/panels/ar.js

B #4234: Fix AR for Virtual Network Templates

---

src/sunstone/public/app/tabs/oneflow-templates-tab/utils/role-tab.js
src/sunstone/public/app/tabs/oneflow-templates-tab/utils/role-tab/html.hbs
src/sunstone/public/app/utils/lock.js
src/sunstone/public/scss/_settings.scss

F #4276: Add button to enable/disable an input

---

src/sunstone/public/app/tabs/vms-tab/dialogs/migrate.js

B #4286: Fix live migration in Sunstone

---

src/sunstone/public/app/opennebula/vm.js

this PR apply:
- master
- one-5.10

Fix RDP: 1 nic

---

src/vmm_mad/remotes/vcenter/reconfigure

B #4194: vCenter context data refresh NIC (alias) detach

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/vcenter/vcenterrc

F #1188: create snapshots without memory dumps

---

src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js
src/sunstone/public/app/tabs/vms-tab/actions.js
src/sunstone/public/app/tabs/vms-tab/form-panels/create.js
src/sunstone/public/app/tabs/vms-tab/utils/datatable-common.js
src/sunstone/public/app/utils/custom-tags-table.js
src/sunstone/public/app/utils/leases.js
src/sunstone/public/bower.json

B # 4132 rename vars and fix charter

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/numa.js

B #4323: Fix NUMA tab switcher

---

src/scheduler/etc/sched.conf

Signed-off-by: kvaps <kvapss@gmail.com>

B #~: uppercase keys sched.conf

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js

B #4278: Fix VM templates in Sunstone
Applies to 5.10 also

B #4274: Fix VM templates in Sunstone

---

src/sunstone/public/app/tabs/provision-tab.js
src/sunstone/public/app/utils/tab-datatable.js

B #1388: Fix vms and images user can see

---

src/sunstone/public/app/tabs/provision-tab.js

Introduced in OpenNebula/one/commit/9f2860c6b3eb4acf5f0f5e777f66ba8df8d54aae

M #~: Removing unneeded OneFlow changes

---

src/sunstone/public/app/tabs/oneflow-templates-tab/form-panels/create.js

B #4273: Fix labels when service update

---

src/onedb/fsck/quotas.rb

B #4328: fsck quotas skip vnet with no ID

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #4150: show template name in vCenter

---

src/onedb/onedb_live.rb

B #4337: add onedb update body readable errors

---

include/HostShare.h
src/host/Host.cc
src/host/HostShare.cc
src/im/InformationManager.cc

F #3859: Update host reservations only if needed

---

share/etc/oned.conf
src/im/InformationManager.cc
src/im_mad/remotes/kvm-probes.d/vms/status/state.rb
src/monitor/src/monitor/HostMonitorManager.cc
src/template/OpenNebulaTemplate.cc

And remove obsolete settings from oned.conf, change some log messages

F 3859 Fix VM_STATE monitoring

---

src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb

F #4150: save as template with template name

---

src/docker_machine/src/docker_machine/opennebula.go

B #4052: use VM ID

---

src/oca/ruby/opennebula/group.rb

B #3361: create group without permissions

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb
src/vmm_mad/remotes/vcenter/deploy

F #1193: differentiate created templates on vCenter

---

share/start-scripts/cron_start_script
share/start-scripts/map_vnets_start_script

New script to be used as start script on virtual machines. It get all
NIC_ALIAS IPs associated to NIC IPs of a service using OneGate, and
install iptables SNAT and DNAT rules to get connectivity with the VM
using the ALIAS_NIC IP.

F #-: Floating IPs start script

---

share/start-scripts/map_vnets_start_script

L #-: Floating IPs start script

---

src/sunstone/public/app/opennebula/vm.js
src/sunstone/public/app/tabs/vms-tab/utils/datatable-common.js
src/sunstone/public/app/utils/labels/utils.js
src/sunstone/public/app/utils/template-utils.js

This PR apply:
-Master
-One-5.10

M #~: fix roles in services

---

src/sunstone/public/app/opennebula/vm.js

M #~: fix var names

---

src/sunstone/public/app/opennebula/vm.js

This PR apply:
- master
- one-5.10

M #~: lost vars in spice Support

---

src/sunstone/public/app/utils/schedule_action.js

B #4380: Fix scheduler actions

---

src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb

F #3675: edit virtual network context fails

---

src/flow/lib/LifeCycleManager.rb
src/flow/lib/models/service.rb

B #4406: respect gid and uig when scaling

---

share/install_gems/install_gems

B #4426: create symlink to libxml

---

src/sunstone/public/app/tabs/vnets-tab/utils/ar-tab.js

This PR apply to:
- master
- one-5.10

B #3615: IPv4 not required when use IPAM

---

src/rm/Request.cc
src/um/UserPool.cc

B 4416: Fix restricted params for UserTemplate

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #4207: fix unmanage nics at deploy time

---

src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb

B #-: Fixes uplink error importing templates.

---

src/sunstone/OpenNebulaVNC.rb

B #4392: Detect VNC proxy under Apache Passenger

---

include/Template.h
src/acl/AclManager.cc
src/host/HostShare.cc
src/market/MarketPlace.cc
src/market/MarketPlaceApp.cc
src/market/MarketPlaceAppPool.cc
src/rm/RequestManager.cc
src/rm/RequestManagerVirtualNetwork.cc
src/rm/RequestManagerVirtualRouter.cc
src/sql/MySqlDB.cc
src/vm/VirtualMachineDisk.cc
src/vnm/AddressRangePool.cc

Merge into 5.10
It should go also to master, but there will be conflicts in HostShare

B #4154: Fix memory leaks

---

share/start-scripts/map_vnets_start_script

M #-: map vnets compatible with OneGate

---

src/sunstone/public/app/utils/panel/template-table.js

This PR apply to:
-  master
- one-5.10

B #2763: vCenter attributes edit icons

---

share/start-scripts/cron_start_script
share/start-scripts/map_vnets_start_script

Added option to provide a configuration scripts with defining IPs for
private and public networks.

M #-: Redesign of map vnets mapping script

---

src/sunstone/public/app/utils/nics-section.js

B #4409: Fix template context vars

---

install.sh

M #-: Install files on share/start-scripts

---

src/sunstone/public/app/utils/schedule_action.js

M #~: Fix html scheduling action table

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine_monitor/vm_monitor.rb

F #3316: monitor disk location in vCenter

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/os/html.hbs

F #3025: LXD template clean section

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/actions.js
src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js
src/sunstone/public/app/tabs/vms-tab/panels/actions.js
src/sunstone/public/app/utils/schedule_action.js
src/sunstone/public/app/utils/schedule_action/html.hbs

F #2340: add ARGS in schedule actions

---

src/cli/oneflow
src/flow/lib/LifeCycleManager.rb
src/flow/oneflow-server.rb

B #4491: update role info when terminating it

---

share/oneprovision/ansible/dummy.yml
src/cli/one_helper/oneprovision_helper.rb
src/oneprovision/lib/ansible.rb
src/oneprovision/lib/provision.rb
src/oneprovision/lib/resources/physical/host.rb
src/oneprovision/lib/resources/resource.rb
src/oneprovision/lib/resources/virtual/flowtemplate.rb
src/oneprovision/lib/utils.rb

F #4292: DDC add support for multiple playbooks

---

src/sunstone/public/app/opennebula/service.js
src/sunstone/public/app/tabs/oneflow-services-tab/actions.js

applies to: 
- master
- one-5.10

B #4487: Remove done services in sunstone

---

src/sunstone/public/app/tabs/hosts-tab/datatable.js
src/sunstone/public/app/tabs/hosts-tab/utils/reserved.js

B #4256: Fix capacity bars

---

src/onedb/fsck.rb
src/onedb/fsck/network.rb

B #4512: Fixed onedb fsck ip6 leases check

---

src/sunstone/etc/sunstone-views/kvm/admin.yaml
src/sunstone/etc/sunstone-views/kvm/groupadmin.yaml
src/sunstone/etc/sunstone-views/kvm/user.yaml
src/sunstone/etc/sunstone-views/mixed/admin.yaml
src/sunstone/etc/sunstone-views/mixed/groupadmin.yaml
src/sunstone/etc/sunstone-views/mixed/user.yaml
src/sunstone/etc/sunstone-views/vcenter/admin.yaml
src/sunstone/etc/sunstone-views/vcenter/groupadmin.yaml
src/sunstone/etc/sunstone-views/vcenter/user.yaml
src/sunstone/public/app/opennebula/action.js
src/sunstone/public/app/tabs/oneflow-services-tab.js
src/sunstone/public/app/tabs/oneflow-services-tab/panels/sched-actions/html.hbs
src/sunstone/public/app/tabs/oneflow-services-tab/panels/sched-actions/panelId.js
src/sunstone/public/app/tabs/oneflow-services-tab/panels/sched_actions.js

F #2340: add sched_action in flow

---

install.sh
src/im_mad/remotes/one-probes.d/host/monitor/probe_host_monitor.rb
src/im_mad/remotes/one-probes.d/host/system/probe_host_system.rb
src/im_mad/remotes/one-probes.d/vm/monitor/probe_vm_monitor.rb
src/im_mad/remotes/one-probes.d/vm/status/probe_vm_status.rb
src/im_mad/remotes/one.d/monitord-client.rb
src/im_mad/remotes/one.d/monitord-client_control.sh
src/mad/ruby/PublicCloudDriver.rb
src/vmm_mad/remotes/az/az_driver.rb
src/vmm_mad/remotes/ec2/ec2_driver.rb
src/vmm_mad/remotes/one/deploy
src/vmm_mad/remotes/one/opennebula_driver.rb
src/vmm_mad/remotes/one/reboot
src/vmm_mad/remotes/one/reset
src/vmm_mad/remotes/one/save
src/vmm_mad/remotes/one/shutdown

I renamed OpenNebulaDriver to One2OneDriver as there was a name conflict in the class hierarchy

F #3859: Adopt one2one driver to new monitoring

---

src/sunstone/public/scss/_table.scss

M #~: styles in icons vms

---

src/sunstone/public/app/utils/nics-section.js

B #4284: Nics lost after making  save as

---

src/sunstone/public/app/tabs/marketplaces-tab/form-panels/create.js
src/sunstone/public/app/tabs/marketplaces-tab/form-panels/create/wizard.hbs

F #3059: LXD marketplace attributes

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/storage/disk-tab/options.hbs

F #3024: Change target device fieldname

---

src/sunstone/public/app/opennebula/action.js
src/sunstone/public/app/tabs/oneflow-services-tab/panels/sched_actions.js

M #~: fix document id

---

share/doc/xsd/index.xsd
share/doc/xsd/showback.xsd

B #4148: Added missing showback xsd

---

src/sunstone/public/app/utils/nics-section.js

F #4532: Fix data nics template

---

install.sh
share/oneprovision/examples/example_ec2.yaml
share/oneprovision/examples/example_packet.yaml

F #4215: add packet and ec2 example templates

---

src/im_mad/remotes/vcenter.d/monitord-client.rb
src/im_mad/remotes/vcenter.d/monitord-client_control.sh

Change monitord-client.rb and monitord-client-control.sh
Add vCenter to LOCAL_HYPERVISOR variable.

F #4302: Change monitord-clients

---

src/sunstone/public/app/tabs/vms-tab/utils/datatable-common.js

M #~: fix VM charter time

---

src/sunstone/public/app/tabs/vrouters-tab/panels/info/html.hbs

B #4147: vRouter floating IP

---

src/sunstone/public/app/tabs/dashboard-tab.js

B #2504: Fix vms widget on dashboard

---

src/vmm_mad/remotes/vcenter/deploy

L #3912: lint deploy

---

src/sunstone/public/app/tabs/settings-tab/panels/user-config.js
src/sunstone/public/app/tabs/settings-tab/panels/user-config/html.hbs
src/sunstone/public/app/tabs/users-tab/dialogs/password.js
src/sunstone/public/app/tabs/users-tab/dialogs/password/html.hbs

F #4327: block pwd change admin acct

---

share/oneprovision/ansible/roles/opennebula-ssh/defaults/main.yml
share/oneprovision/ansible/roles/opennebula-ssh/tasks/deploy_local.yml
share/pkgs/services/systemd/opennebula-ssh-agent.service
share/pkgs/services/systemd/opennebula.service
src/mad/sh/scripts_common.sh

F #2152: Add OpenNebula SSH agent support

---

src/sunstone/public/app/utils/schedule_action.js

M #-: fix selector val

---

src/sunstone/public/app/utils/nics-section.js

this PR apply:
- master
(In this PR, place the NETWORK field to the VM, when the instance was deleted, but if the NETWORK_UNAME does not exist in the template, it will not reach the VM. And then it will not be able to instantiate if the owner of the NIC is not the same as the one that is instantiated)

M #~: preserve NETWORK name intantiate

---

src/sunstone/models/OpenNebulaJSON/VirtualNetworkJSON.rb
src/sunstone/public/app/tabs/vnets-tab/panels/ar.js

F #2837: Force AR remove

---

src/mad/sh/scripts_common.sh
src/tm_mad/ceph/premigrate
src/tm_mad/ssh/clone
src/tm_mad/ssh/cpds
src/tm_mad/ssh/mv
src/tm_mad/ssh/mvds

F #2152: Restrict SSH agent forwarding

---

src/sunstone/public/app/sunstone-config.js
src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate/templateRow.hbs
src/sunstone/public/app/templates/helpers/isOneFeatureEnabled.js

B #3604: Hide instantiate options

---

src/sunstone/etc/sunstone-server.conf
src/sunstone/public/app/sunstone-config.js
src/sunstone/public/app/tabs/hosts-tab/datatable.js
src/sunstone/views/index.erb

F #4068: Dashboard Thresholds

---

src/onedb/onedb.rb

before falling back to interactive

F #2514 look for ONE_DB_PASSWORD environment var

---

src/im_mad/remotes/az-probes.d/vm/status/probe_vm_status.rb
src/im_mad/remotes/ec2-probes.d/vm/status/probe_vm_status.rb
src/im_mad/remotes/firecracker-probes.d/vm/status/state.rb
src/im_mad/remotes/kvm-probes.d/vm/status/state.rb
src/im_mad/remotes/lib/probe_db.rb
src/im_mad/remotes/lxd-probes.d/vm/status/state.rb
src/im_mad/remotes/one-probes.d/vm/status/probe_vm_status.rb
src/im_mad/remotes/packet-probes.d/vm/status/probe_vm_status.rb
src/im_mad/remotes/vcenter-probes.d/vms/status/state.rb

Change to allow one status database per host avoiding locks

F #4302: Creates a status db for each host

---

src/vm/VirtualMachineParser.cc

This PR applies to 5.10 and master.

B #4103: crop size of spice random password

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #4474: preparing vCPU for numa and pinning

---

share/augeas/oned.aug
share/augeas/test_oned.aug

Copy the results to onescape repo

M #-: accept quotes in augeas lens

---

src/sunstone/public/app/tabs/vms-tab/datatable.js
src/sunstone/public/app/tabs/vms-tab/utils/datatable-common.js
src/sunstone/public/app/utils/schedule_action.js

M #-: add tooltip Charters

---

install.sh
src/im_mad/remotes/lib/vcenter.rb
src/im_mad/remotes/vcenter-probes.d/vms/monitor/monitor.rb
src/vmm_mad/remotes/lib/vcenter_driver/vcenter_driver.conf
tep

VM monitoring working, except:
- Resource pools info
- c98f89492 - F #3316: monitor disk location in vCenter (#4476)
Prepare to use cache retrieveing vcenter virtualmachines

F #4302: VM monitoring working

---

src/sunstone/public/app/tabs/hosts-tab/panels/wilds.js
src/sunstone/public/app/tabs/hosts-tab/panels/wilds/html.hbs

F #4161: wilds VM search

---

src/sunstone/public/app/tabs/provision-tab/vms/list.js
src/sunstone/public/app/tabs/vms-tab/utils/datatable-common.js

M #~: add charters in cloud view

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/numa.js

M #~: fix fill data hugepages

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/numa.js

This PR Apply:
- master
- one-5.10

M #~: replace name position

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

F #4474: rename CORES to CORES_PER_SOCKET

---

src/sunstone/public/app/tabs/provision-tab.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create-common.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/general/capacity-create.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/general/capacity-create/html.hbs
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/general/capacity-inputs.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/general/capacity-inputs/html.hbs
src/sunstone/public/app/tabs/templates-tab/form-panels/instantiate.js
src/sunstone/public/app/tabs/vms-tab/dialogs/resize.js
src/sunstone/public/app/tabs/vms-tab/panels/capacity.js
src/sunstone/public/app/tabs/vms-tab/panels/capacity/html.hbs

F #4474: Cores vCenter

---

src/sunstone/public/app/tabs/hosts-tab/panels/info.js
src/sunstone/public/app/tabs/hosts-tab/utils/cpu-bars.js
src/sunstone/public/app/tabs/hosts-tab/utils/memory-bars.js
src/sunstone/public/app/tabs/hosts-tab/utils/reserved.js

B #1756: replace MAX_CPU for TOTAL_CPU

---

src/sunstone/public/app/opennebula/vm.js
src/sunstone/public/app/tabs/vms-tab/datatable.js
src/sunstone/public/app/tabs/vms-tab/utils/datatable-common.js
src/sunstone/public/app/utils/tab-datatable.js

F #1417: VM IPs Dropdown

---

src/vmm_mad/remotes/ec2/ec2_driver.conf

Probably not exhaustive.
Signed-off-by: Dave Love <dave.love@manchester.ac.uk>

Update EC2 driver list

---

src/sunstone/public/app/opennebula/vm.js

M #~: fix lost var ips

---

src/im_mad/remotes/common.d/monitord-client.rb
src/monitor/etc/monitord.conf
src/monitor/src/monitor/Monitor.cc
src/monitor/src/monitor/MonitorConfigTemplate.cc

Disable dummy driver
Change beacon period to 30 s

F #3859: Rename monitor UDP_LISTENER->NETWORK

---

src/sunstone/public/scss/app.scss

B #2126: limit charactes error

---

src/host/HostShareNUMA.cc
src/im/InformationManager.cc

* Remove host_share values from template
* Fix typo in wilds handling

F 3859 Small fixes in monitoring

---

src/sunstone/public/app/opennebula/vm.js

B #1417: Fix VM IPs Dropdown

---

src/sunstone/public/app/opennebula/vm.js
src/sunstone/public/app/sunstone.js
src/sunstone/public/app/sunstone/buttons.hbs
src/sunstone/public/app/sunstone/panels.hbs
src/sunstone/public/app/tabs/vms-tab/actions.js
src/sunstone/public/app/tabs/vms-tab/buttons.js
src/sunstone/public/app/tabs/vms-tab/panels/capacity.js
src/sunstone/public/app/tabs/vms-tab/panels/network.js
src/sunstone/public/app/tabs/vms-tab/panels/snapshots.js
src/sunstone/public/app/tabs/vms-tab/panels/storage.js
src/sunstone/public/app/tabs/vms-tab/panels/storage/disk-details.hbs
src/sunstone/public/app/tabs/vms-tab/panels/storage/html.hbs

Firecracker vm actions

---

src/sunstone/public/app/tabs/vms-tab/panels/network.js

M #4089: fix lost var

---

src/sunstone/public/app/tabs/hosts-tab/panels/numa.js
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine_monitor/vm_monitor.rb

B #4474: Hide NUMA tab vcenter

---

src/sunstone/public/app/tabs/oneflow-services-tab/panels/sched-actions/html.hbs
src/sunstone/public/app/tabs/oneflow-services-tab/panels/sched_actions.js

M #~: remove period and number flow

---

share/etc/cron.d/opennebula-node
share/etc/cron.d/opennebula-ssh-socks-cleaner
share/pkgs/ssh/config
share/pkgs/ssh/config-pre7.6

- workaround issues with persistent connections
- add new cronjob

F #1473: Fix and improve SSH config

---

src/sunstone/etc/sunstone-server.conf
src/sunstone/public/app/sunstone.js
src/sunstone/public/app/tabs/provision-tab.js
src/sunstone/public/app/tabs/provision-tab/flows/list.js
src/sunstone/public/app/tabs/provision-tab/templates/list.js
src/sunstone/public/app/tabs/provision-tab/vms/list.js
src/sunstone/views/index.erb

F #4126: custom paginate cloudview

---

src/vmm_mad/remotes/lib/vcenter_driver/host.rb
src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine_monitor/vm_monitor.rb

- Fix problem and now all vms are monitored
- one-xx in vCenter needs to be renamed to be detected as wilds

F #4302: Multiple vm monitoring working

---

src/sunstone/public/app/tabs/oneflow-templates-tab/form-panels/create.js

M #~: Fix input network names in flow template

---

src/vnm_mad/remotes/dummy/clean
src/vnm_mad/remotes/dummy/post
src/vnm_mad/remotes/dummy/pre

Synchronize PATH override with Ruby drivers
https://github.com/OpenNebula/one/blob/48c3ee1f23dbe6544c9c675032403cb68321f0ca/src/vnm_mad/remotes/lib/vnmmad.rb#L59

M #-: Restrict sudo ip usage

---

src/cli/one_helper/onehost_helper.rb
src/host/Host.cc
src/im/InformationManager.cc
src/im_mad/remotes/lib/kvm.rb
src/im_mad/remotes/lib/lxd.rb
src/im_mad/remotes/lib/probe_db.rb
src/monitor/src/monitor/HostMonitorManager.cc
src/monitor/src/monitor/MonitorDriverProtocol.cc
src/vm/VirtualMachine.cc
src/vm/VirtualMachinePool.cc

todo:
* fix lxd monitor probe
* make similar changes for firecracker and vCenter

F #3859: Use DEPLOY_ID for wilds

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/network/nic-tab/html.hbs
src/sunstone/public/app/utils/nics-section.js
src/sunstone/public/app/utils/nics-section/dd.hbs

F 3102: Disable Network "Automatic selection" on VM template instantiation screen

---

src/sunstone/etc/sunstone-views/kvm/admin.yaml
src/sunstone/etc/sunstone-views/kvm/groupadmin.yaml
src/sunstone/etc/sunstone-views/kvm/user.yaml
src/sunstone/etc/sunstone-views/mixed/admin.yaml
src/sunstone/etc/sunstone-views/mixed/groupadmin.yaml
src/sunstone/etc/sunstone-views/mixed/user.yaml
src/sunstone/etc/sunstone-views/vcenter/admin.yaml
src/sunstone/etc/sunstone-views/vcenter/groupadmin.yaml
src/sunstone/etc/sunstone-views/vcenter/user.yaml
src/sunstone/public/app/tabs/vnets-tab.js
src/sunstone/public/app/tabs/vnets-tab/actions.js
src/sunstone/public/app/tabs/vnets-tab/dialogs/add-secgroups.js
src/sunstone/public/app/tabs/vnets-tab/dialogs/add-secgroups/dialogId.js
src/sunstone/public/app/tabs/vnets-tab/dialogs/add-secgroups/html.hbs
src/sunstone/public/app/tabs/vnets-tab/panels/secgroups.js
src/sunstone/public/app/tabs/vnets-tab/panels/secgroups/html.hbs
src/sunstone/public/app/tabs/vnets-tab/utils/secgroups-tab.js
src/sunstone/public/app/tabs/vnets-tab/utils/secgroups-tab/html.hbs

F #4453: Sec. Groups VNets

---

src/sunstone/public/app/tabs/provision-tab.js

F #2496: Force IPv4 Cloud View

---

src/im_mad/remotes/lib/lxd.rb
src/im_mad/remotes/lxd-probes.d/vm/status/state.rb

- Moved LXD to ONE status mapping to Domain
- Updated wild import template with status

 F #3859: Add import state for Wild LXD containers

---

src/sunstone/public/app/tabs/hosts-tab/panels/wilds.js

M #~ fix error import wilds vcenter

---

src/sunstone/public/app/tabs/provision-tab.js
src/sunstone/public/app/tabs/provision-tab/dashboard/quotas.hbs
src/sunstone/public/app/utils/quotas/quota-widgets.js

F #1946: add quotas

---

src/sunstone/public/app/tabs/vms-tab/panels/network.js

F #4290: Save State of IPs Display

---

share/doc/xsd/index.xsd
share/doc/xsd/raftstatus.xsd

B #4741: Added raftstatus xsd

---

src/docker_machine/src/docker_machine/opennebula.go

B #4734: fix driver breaking change

---

src/sunstone/public/app/utils/menu/top-row.hbs
src/sunstone/public/scss/_layout.scss
src/sunstone/public/scss/app.scss

M #~: center logo in menu

---

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/storage/disk-tab.js
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/storage/disk-tab/html.hbs
src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/storage/disk-tab/options.hbs
src/sunstone/public/app/utils/user-inputs.js

F #1487: Allow TB on disks

---

src/datastore_mad/remotes/lxd_downloader.sh
src/market_mad/remotes/linuxcontainers/monitor

This commit adds support for ALT Linux lxd containers images from Linux Containers Market.

add ALT Linux support

---

src/docker_machine/src/docker_machine/opennebula.go

B #4734: Docker-machine code enhancement (#4789)

---

src/sunstone/public/app/tabs/vnets-tab/panels/leases.js
src/sunstone/public/app/tabs/vnets-tab/panels/leases/html.hbs

F #3758: Add VM name in leases

---

src/sunstone/public/app/tabs/hosts-tab/panels/info.js
src/sunstone/public/app/tabs/hosts-tab/panels/nsx.js
src/sunstone/public/app/tabs/hosts-tab/panels/nsx/html.hbs

F #4081: Move NSX attributes

---

src/sunstone/public/app/tabs/oneflow-services-tab/form-panels/create.js
src/sunstone/public/app/tabs/oneflow-templates-tab/form-panels/instantiate.js
src/sunstone/public/app/tabs/oneflow-templates-tab/form-panels/instantiate/html.hbs
src/sunstone/public/app/utils/user-inputs.js

F #2992 assing vmgroups when create a services

---

src/vmm_mad/remotes/lib/vcenter_driver/datacenter.rb
src/vmm_mad/remotes/lib/vcenter_driver/network.rb
src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb
src/vmm_mad/remotes/lib/vcenter_driver/vmm_importer.rb

B #4004: fix NSXV network imported as DPG

---

src/oca/python/setup.py

Revert "M #-: Allow 4 level version in PyONE"

---

src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb

B #4150: unlock VM Templatet in right place

---

src/sunstone/public/app/tabs/vms-tab/dialogs/disk-resize.js
src/sunstone/public/app/utils/range-slider.js
src/sunstone/public/app/utils/range-slider/html.hbs
src/sunstone/public/app/utils/user-inputs.js

B #1487: Fix TB input

---

src/sunstone/public/app/tabs/vms-tab/panels/storage.js

B #1487 remove *1024 disk

---

src/im_mad/remotes/lib/monitord_client.rb

This commit fix sending udp packets in HA environments, after leader change
It was already commited in the past, but it was lost by merging

F #3859: Monitor UDP use send with host and port

---

src/sunstone/public/app/tabs/vms-tab/dialogs/disk-resize.js
src/sunstone/public/app/utils/range-slider.js

B #1487: no gen ticks

---

src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb

M #~: add rescue in template import

---

src/sunstone/public/patches/enterprise/login_enterprise.patch
src/sunstone/views/login.erb

M #-: Login Enterprise patch

---

src/sunstone/public/app/tabs/provision-tab.js

B #1946:  networks is not array

---

src/sunstone/public/app/tabs/hosts-tab/panels/numa.js

M #-:Remove console log

---

src/sunstone/public/app/utils/user-inputs.js

B #2992: remove check description

---

src/um/UserPool.cc

M #~: fix typo in UserPool.cc

---

src/sunstone/public/app/utils/user-inputs.js

M #~: fix fill input with units

---

src/oca/go/src/goca/acl.go
src/oca/go/src/goca/cluster.go
src/oca/go/src/goca/datastore.go
src/oca/go/src/goca/document.go
src/oca/go/src/goca/group.go
src/oca/go/src/goca/hook.go
src/oca/go/src/goca/host.go
src/oca/go/src/goca/image.go
src/oca/go/src/goca/marketplace.go
src/oca/go/src/goca/marketplaceapp.go
src/oca/go/src/goca/securitygroup.go
src/oca/go/src/goca/template.go
src/oca/go/src/goca/user.go
src/oca/go/src/goca/vdc.go
src/oca/go/src/goca/virtualnetwork.go
src/oca/go/src/goca/virtualrouter.go
src/oca/go/src/goca/vm.go
src/oca/go/src/goca/vmgroup.go
src/oca/go/src/goca/vntemplate.go
src/oca/go/src/goca/zone.go

For consistency with previous changes

B #4921: GOCA - 0 is a valid entity ID

---

src/tm_mad/ssh/mv

added white space to fix incorrect syntax

fixed incorrect bash syntax

---

src/sql/MySqlDB.cc

set charset with mysql_option() 
add the database name to mysql_real_connect()
set flag to remember the options in mysql_real_connect()
append th the db_connect array in a single loop

B #5196: fix mysql reconnect

---

src/docker_machine/src/docker_machine/Gopkg.lock
src/docker_machine/src/docker_machine/opennebula.go

- fixed issue with resume vm in pending state
- enhanced GetIP method to minimize API calls
- GetURL  return address only if machine is running
- code cleanup

B #5301: docker-machine enhancements

---

src/oca/go/src/goca/acl.go

I introduced an obvious via my previous PR around ACL creation, my apologises to the ONE team for this

B #5606: GOCA - fix ACL method parameter

---

src/oca/python/Makefile
src/oca/python/pyone/util.py

* remove python2-pyone
* adopt to generateDS 2.39

M #-: PyONE: rename buildChildren _buildChildren (#1393)

---

.gitignore
src/market_mad/one_market.rb

F #5917: Support for proxy in datastore drivers

---

src/oca/go/src/goca/dynamic/dyntemplate.go
src/oca/go/src/goca/dynamic/dyntemplate_test.go
src/oca/go/src/goca/dynamic/unmarshal.go
src/oca/go/src/goca/schemas/virtualnetwork/virtualnetwork.go

I introduced a regression in PR #6055
This PR revert the changes I made and propose an alternative solution.
To reuse existing code I introduced a new type called `Pairs`, which is a subset of a `Vector`, then I use struct embedding to make content and methods from `Pairs` available to `Vector`.
Apologies to the OpenNebula team for the noise around this
Close #6105

F-6105: introduce pairs

---

src/vmm/LibVirtDriverKVM.cc
src/vmm_mad/exec/vmm_exec_kvm.conf

F #6437: Allow to set CPU_MODEL[FEATURES] on host and cluster level

---

src/sunstone/patches/SunstoneViews.patch
src/sunstone/patches/sunstone-server.patch

* Adds two patches needed for running RSunstone on systems with Psych >= 4.0
<hr>

M #-: Add RSunstone patch files

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement-request.md

Update issue templates:
- Remove Type label
- Add Status pending
- Add Type
<hr>

M #-: Update labels and type of issue templates
